"""Unit tests for the autogenerated deck-path configuration module."""

from __future__ import annotations

from fpdb_3_legacy.card_path import deck_path


def test_deck_path_returns_deck_directory() -> None:
    assert deck_path() == "/usr/local"
