"""card_path.py - Autogenerated file for FPDB.
from __future__ import annotations
This module provides deck path configuration for FPDB.
"""


def deck_path() -> str:
    """Return the path to the deck directory.

    Returns:
        str: The path to the deck directory.
    """
    return "/usr/local"
