"""Launch identity that a HUD bug report can be argued from.

A report of "two overlays per player" cannot be settled from the application
log as it stands: several launches share one file, the HUD child and the GUI
parent look alike, and nothing says which executable actually ran. Every
question that matters -- which build, which process, how many of them, run from
where -- is answered by the few facts collected here and written once per
process as a banner.

The session id is generated by whichever process starts first and passed to
children through the environment, so the parent GUI and its HUD child share
one id while a relaunch gets a new one. That is what makes "separate the logs
by session" a grep rather than a guess.
"""

from __future__ import annotations

import os
import sys
import uuid
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import logging

# macOS runs a quarantined app from a read-only, randomly named mount instead
# of where the user put it. The mount path is the only visible sign of it, and
# it also explains TCC grants that silently stop applying after an update.
APP_TRANSLOCATION_MARKER = "/AppTranslocation/"

#: Children inherit the launch id through this variable.
SESSION_ENV_VAR = "FPDB_SESSION_ID"

#: Values accepted for the ``role`` field of an identity banner.
ROLE_MAIN = "main"
ROLE_HUD = "hud"


def session_id() -> str:
    """Return the id shared by every log line of this launch.

    Generated on first use and exported, so a process spawned later in the
    same launch reports the same id rather than opening a session of its own.
    """
    existing = os.environ.get(SESSION_ENV_VAR)
    if existing:
        return existing
    generated = uuid.uuid4().hex[:12]
    os.environ[SESSION_ENV_VAR] = generated
    return generated


def executable_path() -> str:
    """Return the real path of the running executable.

    ``sys.executable`` is what was asked for; the resolved path is what ran,
    and the two differ exactly in the cases worth logging -- a symlink into a
    bundle, or a translocated mount.
    """
    try:
        return str(Path(sys.executable).resolve())
    except OSError:
        return str(sys.executable)


def is_app_translocated(path: str | os.PathLike[str] | None = None) -> bool:
    """Whether the given executable path is running under App Translocation."""
    candidate = executable_path() if path is None else str(path)
    return APP_TRANSLOCATION_MARKER in candidate


def bundle_path(path: str | os.PathLike[str] | None = None) -> str | None:
    """Return the enclosing ``.app`` of an executable, when there is one."""
    candidate = Path(executable_path() if path is None else path)
    for parent in candidate.parents:
        if parent.suffix == ".app":
            return str(parent)
    return None


def app_version() -> str:
    """Return the application version, or ``unknown`` if it cannot be read."""
    try:
        from fpdb_3_legacy import __version__
    except Exception:  # pragma: no cover - a build without the package metadata
        return "unknown"
    return str(__version__)


def process_identity(role: str, command: list[str] | None = None) -> dict[str, Any]:
    """Collect the launch facts of this process.

    Args:
        role: ``main`` for the GUI, ``hud`` for the overlay process.
        command: the argv this process was started with, when the caller knows
            it more precisely than ``sys.argv`` does.

    Returns:
        A mapping written as-is into the banner and reusable by tests.
    """
    executable = executable_path()
    return {
        "session": session_id(),
        "role": role,
        "version": app_version(),
        "pid": os.getpid(),
        "ppid": os.getppid(),
        "executable": executable,
        "frozen": str(getattr(sys, "frozen", False)),
        "bundle": bundle_path(executable),
        "translocated": is_app_translocated(executable),
        "command": list(command) if command is not None else list(sys.argv),
    }


def format_identity(identity: dict[str, Any]) -> str:
    """Render an identity mapping as one greppable line."""
    return " ".join(f"{key}={value!r}" for key, value in identity.items())


def log_process_identity(
    log: logging.Logger,
    role: str,
    command: list[str] | None = None,
) -> dict[str, Any]:
    """Write the launch banner and return the identity it reported.

    At WARNING because the HUD's diagnostics are pinned to that level (see
    ``DIAGNOSTIC_LEVEL_CAP``): a banner that a user's log does not contain is
    a banner that cannot answer anything.
    """
    identity = process_identity(role, command)
    log.warning("FPDB launch identity: %s", format_identity(identity))
    if identity["translocated"]:
        log.warning(
            "This build is running under macOS App Translocation from %s. macOS gives a "
            "translocated app a throwaway identity, so Accessibility and Automation grants "
            "do not apply to it and the HUD cannot read table windows. Move %s to "
            "/Applications and launch it from there.",
            identity["executable"],
            identity["bundle"] or identity["executable"],
        )
    return identity
