"""HandsPlayers persistence query."""

from __future__ import annotations


def hand_player_persistence_queries() -> dict[str, str]:
    """Return the full-width HandsPlayers insert query."""
    query: dict[str, str] = {}
    query["store_hands_players"] = """insert into HandsPlayers (
            handId,
            playerId,
            startCash,
            effStack,
            startBounty,
            endBounty,
            seatNo,
            sitout,
            card1,
            card2,
            card3,
            card4,
            card5,
            card6,
            card7,
            card8,
            card9,
            card10,
            card11,
            card12,
            card13,
            card14,
            card15,
            card16,
            card17,
            card18,
            card19,
            card20,
            common,
            committed,
            winnings,
            rake,
            rakeDealt,
            rakeContributed,
            rakeWeighted,
            totalProfit,
            allInEV,
            street0VPIChance,
            street0VPI,
            street1Seen,
            street2Seen,
            street3Seen,
            street4Seen,
            sawShowdown,
            showed,
            street0AllIn,
            street1AllIn,
            street2AllIn,
            street3AllIn,
            street4AllIn,
            wentAllIn,
            splashWinnings,
            street0AggrChance,
            street0Aggr,
            street1Aggr,
            street2Aggr,
            street3Aggr,
            street4Aggr,
            street1CBChance,
            street2CBChance,
            street3CBChance,
            street4CBChance,
            street1CBDone,
            street2CBDone,
            street3CBDone,
            street4CBDone,
            wonWhenSeenStreet1,
            wonWhenSeenStreet2,
            wonWhenSeenStreet3,
            wonWhenSeenStreet4,
            wonAtSD,
            position,
            street0InPosition,
            street1InPosition,
            street2InPosition,
            street3InPosition,
            street4InPosition,
            street0FirstToAct,
            street1FirstToAct,
            street2FirstToAct,
            street3FirstToAct,
            street4FirstToAct,
            tourneysPlayersId,
            startCards,
            street0CalledRaiseChance,
            street0CalledRaiseDone,
            street0FaceRaise,
            street0_2BChance,
            street0_2BDone,
            street0_3BChance,
            street0_3BDone,
            street0_4BChance,
            street0_4BDone,
            street0_C4BChance,
            street0_C4BDone,
            street0_FoldTo2BChance,
            street0_FoldTo2BDone,
            street0_FoldTo3BChance,
            street0_FoldTo3BDone,
            street0_FoldTo4BChance,
            street0_FoldTo4BDone,
            street0_SqueezeChance,
            street0_SqueezeDone,
            raiseToStealChance,
            raiseToStealDone,
            stealChance,
            stealDone,
            success_Steal,
            otherRaisedStreet0,
            otherRaisedStreet1,
            otherRaisedStreet2,
            otherRaisedStreet3,
            otherRaisedStreet4,
            foldToOtherRaisedStreet0,
            foldToOtherRaisedStreet1,
            foldToOtherRaisedStreet2,
            foldToOtherRaisedStreet3,
            foldToOtherRaisedStreet4,
            raiseFirstInChance,
            raisedFirstIn,
            foldBbToStealChance,
            foldedBbToSteal,
            foldSbToStealChance,
            foldedSbToSteal,
            foldToStreet1CBChance,
            foldToStreet1CBDone,
            foldToStreet2CBChance,
            foldToStreet2CBDone,
            foldToStreet3CBChance,
            foldToStreet3CBDone,
            foldToStreet4CBChance,
            foldToStreet4CBDone,
            street1CheckCallRaiseChance,
            street1CheckCallDone,
            street1CheckRaiseDone,
            street2CheckCallRaiseChance,
            street2CheckCallDone,
            street2CheckRaiseDone,
            street3CheckCallRaiseChance,
            street3CheckCallDone,
            street3CheckRaiseDone,
            street4CheckCallRaiseChance,
            street4CheckCallDone,
            street4CheckRaiseDone,
            street0Calls,
            street1Calls,
            street2Calls,
            street3Calls,
            street4Calls,
            street0Bets,
            street1Bets,
            street2Bets,
            street3Bets,
            street4Bets,
            street0Raises,
            street1Raises,
            street2Raises,
            street3Raises,
            street4Raises,
    street1Discards,
             street2Discards,
             street3Discards,
             street0Limp,
             street0OpenLimp,
             handString,
             cashOutFee,
             isCashOut,
             street1_3BChance,
             street1_3BDone,
             street2_3BChance,
             street2_3BDone,
             street3_3BChance,
             street3_3BDone,
             street1_4BChance,
             street1_4BDone,
             street1_FoldTo4BChance,
             street1_FoldTo4BDone,
             street2_4BChance,
             street2_4BDone,
             street2_FoldTo4BChance,
             street2_FoldTo4BDone,
             street3_4BChance,
             street3_4BDone,
             street3_FoldTo4BChance,
             street3_FoldTo4BDone,
             street1OpenChance,
             street1OpenDone,
             street2OpenChance,
             street2OpenDone,
             street3OpenChance,
             street3OpenDone,
             flg_f_fold,
             flg_t_fold,
             flg_r_fold,
             street1FirstRaise,
             street2FirstRaise,
             street3FirstRaise,
             street1FaceRaise,
             street2FaceRaise,
             street3FaceRaise,
             flg_f_donk_def_opp,
             flg_t_float_opp,
             flg_t_float,
             flg_t_float_def_opp,
             flg_r_float_opp,
             flg_r_float,
             flg_r_float_def_opp,
             flg_t_donk_def_opp,
             flg_r_donk_def_opp,
             street1_FoldTo3BChance,
             street1_FoldTo3BDone,
             street2_FoldTo3BChance,
             street2_FoldTo3BDone,
             street3_FoldTo3BChance,
             street3_FoldTo3BDone,
             street0_FoldToSqueezeChance,
             street0_FoldToSqueezeDone,
             street0_FaceLimpers,
             cnt_gp_open_opp,
             cnt_gp_2x,
             cnt_gp_os,
             cnt_gp_limp,
             flg_blind_ds,
             flg_blind_db,
             flg_blind_k,
             flg_faced_allin,
             flg_fold_to_allin,
             cnt_f_bet_facing,
             val_f_bet_facing_bp,
             cnt_t_bet_facing,
             val_t_bet_facing_bp,
             cnt_r_bet_facing,
             val_r_bet_facing_bp,
             cnt_p_2bet_facing,
             val_p_2bet_facing_bp,
             cnt_p_3bet_facing,
             val_p_3bet_facing_bp,
             cnt_p_4bet_facing,
             val_p_4bet_facing_bp,
             cnt_f_bet_made,
             val_f_bet_made_bp,
             cnt_t_bet_made,
             val_t_bet_made_bp,
             cnt_r_bet_made,
             val_r_bet_made_bp,
             cnt_f_spr,
             val_f_spr,
             cnt_t_spr,
             val_t_spr,
             cnt_r_spr,
             val_r_spr,
             cnt_p_raise_made,
             val_p_raise_made_bp,
             cnt_f_raise_made,
             val_f_raise_made_bp,
             cnt_t_raise_made,
             val_t_raise_made_bp,
             cnt_r_raise_made,
             val_r_raise_made_bp,
             cnt_f_2bet_facing,
             val_f_2bet_facing_bp,
             cnt_f_3bet_facing,
             val_f_3bet_facing_bp,
             cnt_f_4bet_facing,
             val_f_4bet_facing_bp,
             cnt_t_2bet_facing,
             val_t_2bet_facing_bp,
             cnt_t_3bet_facing,
             val_t_3bet_facing_bp,
             cnt_t_4bet_facing,
             val_t_4bet_facing_bp,
             cnt_r_2bet_facing,
             val_r_2bet_facing_bp,
             cnt_r_3bet_facing,
             val_r_3bet_facing_bp,
             cnt_r_4bet_facing,
             val_r_4bet_facing_bp,
             amt_blind,
             amt_bet_p,
             amt_bet_f,
             amt_bet_t,
             amt_bet_r,
             amt_bet_ttl,
             cnt_p_raise_facing,
             val_p_raise_facing_bp,
             cnt_f_raise_facing,
             val_f_raise_facing_bp,
             cnt_t_raise_facing,
             val_t_raise_facing_bp,
             cnt_r_raise_facing,
             val_r_raise_facing_bp,
             cnt_p_raise_made_2,
             val_p_raise_made_2_bp,
             cnt_f_raise_made_2,
             val_f_raise_made_2_bp,
             cnt_t_raise_made_2,
             val_t_raise_made_2_bp,
             cnt_r_raise_made_2,
             val_r_raise_made_2_bp,
             cnt_p_5bet_facing,
             val_p_5bet_facing_bp,
             street2DelayedCBChance,
             street2DelayedCBDone,
             street2ProbeChance,
             street2ProbeDone,
             enum_p_3bet_action,
             enum_p_4bet_action,
             enum_p_squeeze_action,
             enum_f_3bet_action,
             enum_f_4bet_action,
             enum_f_cbet_action,
             enum_f_donk_action,
             enum_t_3bet_action,
             enum_t_4bet_action,
             enum_t_cbet_action,
             enum_t_float_action,
             enum_t_donk_action,
             enum_r_3bet_action,
             enum_r_4bet_action,
             enum_r_cbet_action,
             enum_r_float_action,
             enum_r_donk_action,
             enum_face_allin,
             enum_face_allin_action,
             enum_folded
            )
            values (
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s,
                 %s, %s, %s,
                 %s, %s,
                 %s, %s,
                 %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s, %s, %s
            ,
                 %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s,
                 %s, %s, %s, %s, %s)"""
    return query

