"""Tournament-domain schema queries."""

from __future__ import annotations


def tournament_schema_queries(db_server: str) -> dict[str, str]:
    """Return backend-specific DDL for tournament-domain tables."""
    if db_server == "mysql":
        return {
            "createTourneyTypesTable": """CREATE TABLE TourneyTypes (
                        id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        siteId SMALLINT UNSIGNED NOT NULL, FOREIGN KEY (siteId) REFERENCES Sites(id),
                        currency varchar(4),
                        buyIn BIGINT,
                        fee BIGINT,
                        category varchar(9) NOT NULL,
                        limitType char(2) NOT NULL,
                        buyInChips BIGINT,
                        stack varchar(8),
                        maxSeats INT,
                        rebuy BOOLEAN,
                        rebuyCost BIGINT,
                        rebuyFee BIGINT,
                        rebuyChips BIGINT,
                        addOn BOOLEAN,
                        addOnCost BIGINT,
                        addOnFee BIGINT,
                        addOnChips BIGINT,
                        knockout BOOLEAN,
                        koBounty BIGINT,
                        progressive BOOLEAN,
                        step BOOLEAN,
                        stepNo INT,
                        chance BOOLEAN,
                        chanceCount INT,
                        speed varchar(10),
                        shootout BOOLEAN,
                        matrix BOOLEAN,
                        multiEntry BOOLEAN,
                        reEntry BOOLEAN,
                        fast BOOLEAN,
                        newToGame BOOLEAN,
                        homeGame BOOLEAN,
                        split BOOLEAN,
                        sng BOOLEAN,
                        fifty50 BOOLEAN,
                        time BOOLEAN,
                        timeAmt INT,
                        satellite BOOLEAN,
                        doubleOrNothing BOOLEAN,
                        cashOut BOOLEAN,
                        onDemand BOOLEAN,
                        flighted BOOLEAN,
                        guarantee BOOLEAN,
                        guaranteeAmt BIGINT,
                        lottery BOOLEAN DEFAULT FALSE,
                        multiplier INT DEFAULT 1)
                        ENGINE=INNODB""",
            "createBackingsTable": "CREATE TABLE Backings (\n                        id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),\n                        tourneysPlayersId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (tourneysPlayersId) REFERENCES TourneysPlayers(id),\n                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),\n                        buyInPercentage FLOAT UNSIGNED NOT NULL,\n                        payOffPercentage FLOAT UNSIGNED NOT NULL) ENGINE=INNODB",
            "createTourneysTable": """CREATE TABLE Tourneys (
                        id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        tourneyTypeId SMALLINT UNSIGNED NOT NULL, FOREIGN KEY (tourneyTypeId) REFERENCES TourneyTypes(id),
                        sessionId INT UNSIGNED, FOREIGN KEY (sessionId) REFERENCES Sessions(id),
                        siteTourneyNo BIGINT NOT NULL,
                        entries INT,
                        prizepool BIGINT,
                        startTime DATETIME,
                        endTime DATETIME,
                        tourneyName TEXT,
                        totalRebuyCount INT,
                        totalAddOnCount INT,
                        added BIGINT,
                        addedCurrency VARCHAR(4),
                        comment TEXT,
                        commentTs DATETIME)
                        ENGINE=INNODB""",
            "createTourneysPlayersTable": """CREATE TABLE TourneysPlayers (
                        id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        tourneyId INT UNSIGNED NOT NULL, FOREIGN KEY (tourneyId) REFERENCES Tourneys(id),
                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        entryId INT,
                        rank INT,
                        winnings BIGINT,
                        winningsCurrency VARCHAR(4),
                        rebuyCount INT,
                        addOnCount INT,
                        koCount NUMERIC,
                        comment TEXT,
                        commentTs DATETIME)
                        ENGINE=INNODB""",
        }
    if db_server == "postgresql":
        return {
            "createTourneyTypesTable": """CREATE TABLE TourneyTypes (
                        id SERIAL, PRIMARY KEY (id),
                        siteId INT NOT NULL, FOREIGN KEY (siteId) REFERENCES Sites(id),
                        currency varchar(4),
                        buyin BIGINT,
                        fee BIGINT,
                        category varchar(9),
                        limitType char(2),
                        buyInChips BIGINT,
                        stack varchar(8),
                        maxSeats INT,
                        rebuy BOOLEAN,
                        rebuyCost BIGINT,
                        rebuyFee BIGINT,
                        rebuyChips BIGINT,
                        addOn BOOLEAN,
                        addOnCost BIGINT,
                        addOnFee BIGINT,
                        addOnChips BIGINT,
                        knockout BOOLEAN,
                        koBounty BIGINT,
                        progressive BOOLEAN,
                        step BOOLEAN,
                        stepNo INT,
                        chance BOOLEAN,
                        chanceCount INT,
                        speed varchar(10),
                        shootout BOOLEAN,
                        matrix BOOLEAN,
                        multiEntry BOOLEAN,
                        reEntry BOOLEAN,
                        fast BOOLEAN,
                        newToGame BOOLEAN,
                        homeGame BOOLEAN,
                        split BOOLEAN,
                        sng BOOLEAN,
                        fifty50 BOOLEAN,
                        time BOOLEAN,
                        timeAmt INT,
                        satellite BOOLEAN,
                        doubleOrNothing BOOLEAN,
                        cashOut BOOLEAN,
                        onDemand BOOLEAN,
                        flighted BOOLEAN,
                        guarantee BOOLEAN,
                        guaranteeAmt BIGINT,
                        lottery BOOLEAN DEFAULT FALSE,
                        multiplier INT DEFAULT 1)""",
            "createBackingsTable": "CREATE TABLE Backings (\n                        id BIGSERIAL, PRIMARY KEY (id),\n                        tourneysPlayersId INT NOT NULL, FOREIGN KEY (tourneysPlayersId) REFERENCES TourneysPlayers(id),\n                        playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),\n                        buyInPercentage FLOAT NOT NULL,\n                        payOffPercentage FLOAT NOT NULL)",
            "createTourneysTable": """CREATE TABLE Tourneys (
                        id SERIAL, PRIMARY KEY (id),
                        tourneyTypeId INT, FOREIGN KEY (tourneyTypeId) REFERENCES TourneyTypes(id),
                        sessionId INT, FOREIGN KEY (sessionId) REFERENCES Sessions(id),
                        siteTourneyNo BIGINT,
                        entries INT,
                        prizepool BIGINT,
                        startTime timestamp without time zone,
                        endTime timestamp without time zone,
                        tourneyName TEXT,
                        totalRebuyCount INT,
                        totalAddOnCount INT,
                        added BIGINT,
                        addedCurrency VARCHAR(4),
                        comment TEXT,
                        commentTs timestamp without time zone)""",
            "createTourneysPlayersTable": """CREATE TABLE TourneysPlayers (
                        id BIGSERIAL, PRIMARY KEY (id),
                        tourneyId INT, FOREIGN KEY (tourneyId) REFERENCES Tourneys(id),
                        playerId INT, FOREIGN KEY (playerId) REFERENCES Players(id),
                        entryId INT,
                        rank INT,
                        winnings BIGINT,
                        winningsCurrency VARCHAR(4),
                        rebuyCount INT,
                        addOnCount INT,
                        koCount NUMERIC,
                        comment TEXT,
                        commentTs timestamp without time zone)""",
        }
    if db_server == "sqlite":
        return {
            "createTourneyTypesTable": """CREATE TABLE TourneyTypes (
                        id INTEGER PRIMARY KEY,
                        siteId INT NOT NULL,
                        currency VARCHAR(4),
                        buyin INT,
                        fee INT,
                        category TEXT,
                        limitType TEXT,
                        buyInChips INT,
                        stack VARCHAR(8),
                        maxSeats INT,
                        rebuy BOOLEAN,
                        rebuyCost INT,
                        rebuyFee INT,
                        rebuyChips INT,
                        addOn BOOLEAN,
                        addOnCost INT,
                        addOnFee INT,
                        addOnChips INT,
                        knockout BOOLEAN,
                        koBounty INT,
                        progressive BOOLEAN,
                        step BOOLEAN,
                        stepNo INT,
                        chance BOOLEAN,
                        chanceCount INT,
                        speed TEXT,
                        shootout BOOLEAN,
                        matrix BOOLEAN,
                        multiEntry BOOLEAN,
                        reEntry BOOLEAN,
                        fast BOOLEAN,
                        newToGame BOOLEAN,
                        homeGame BOOLEAN,
                        split BOOLEAN,
                        sng BOOLEAN,
                        fifty50 BOOLEAN,
                        time BOOLEAN,
                        timeAmt INT,
                        satellite BOOLEAN,
                        doubleOrNothing BOOLEAN,
                        cashOut BOOLEAN,
                        onDemand BOOLEAN,
                        flighted BOOLEAN,
                        guarantee BOOLEAN,
                        guaranteeAmt INT,
                        lottery BOOLEAN DEFAULT FALSE,
                        multiplier INT DEFAULT 1)""",
            "createBackingsTable": "CREATE TABLE Backings (\n                        id INTEGER PRIMARY KEY,\n                        tourneysPlayersId INT NOT NULL,\n                        playerId INT NOT NULL,\n                        buyInPercentage REAL UNSIGNED NOT NULL,\n                        payOffPercentage REAL UNSIGNED NOT NULL)",
            "createTourneysTable": """CREATE TABLE Tourneys (
                        id INTEGER PRIMARY KEY,
                        tourneyTypeId INT,
                        sessionId INT,
                        siteTourneyNo INT,
                        entries INT,
                        prizepool INT,
                        startTime timestamp,
                        endTime timestamp,
                        tourneyName TEXT,
                        totalRebuyCount INT,
                        totalAddOnCount INT,
                        added INT,
                        addedCurrency VARCHAR(4),
                        comment TEXT,
                        commentTs timestamp)""",
            "createTourneysPlayersTable": """CREATE TABLE TourneysPlayers (
                        id INTEGER PRIMARY KEY,
                        tourneyId INT,
                        playerId INT,
                        entryId INT,
                        rank INT,
                        winnings INT,
                        winningsCurrency VARCHAR(4),
                        rebuyCount INT,
                        addOnCount INT,
                        koCount decimal,
                        comment TEXT,
                        commentTs timestamp,
                        FOREIGN KEY (tourneyId) REFERENCES Tourneys(id),
                        FOREIGN KEY (playerId) REFERENCES Players(id)
                        )""",
        }
    return {}
