"""Per-player poker-hand schema queries."""

from __future__ import annotations


def hand_player_schema_queries(db_server: str) -> dict[str, str]:
    """Return backend-specific DDL for HandsPlayers."""
    if db_server == "mysql":
        ddl = """CREATE TABLE HandsPlayers (
                                id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                                handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                                playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                                startCash BIGINT NOT NULL,
                                effStack BIGINT NOT NULL,
                                startBounty BIGINT,
                                endBounty BIGINT,
                                position CHAR(1),
                                seatNo SMALLINT NOT NULL,
                                sitout BOOLEAN NOT NULL,

                                card1 smallint NOT NULL,  /* 0=none, 1-13=2-Ah 14-26=2-Ad 27-39=2-Ac 40-52=2-As */
                                card2 smallint NOT NULL,
                                card3 smallint,
                                card4 smallint,
                                card5 smallint,
                                card6 smallint,
                                card7 smallint,
                                card8 smallint,  /* cards 8-20 for draw hands */
                                card9 smallint,
                                card10 smallint,
                                card11 smallint,
                                card12 smallint,
                                card13 smallint,
                                card14 smallint,
                                card15 smallint,
                                card16 smallint,
                                card17 smallint,
                                card18 smallint,
                                card19 smallint,
                                card20 smallint,
                                startCards SMALLINT UNSIGNED, FOREIGN KEY (startCards) REFERENCES StartCards(id),

                                common BIGINT NOT NULL,
                                committed BIGINT NOT NULL,
                                winnings BIGINT NOT NULL,
                                rake BIGINT NOT NULL,
                                rakeDealt NUMERIC NOT NULL,
                                rakeContributed NUMERIC NOT NULL,
                                rakeWeighted NUMERIC NOT NULL,
                                totalProfit BIGINT,
                                allInEV NUMERIC,
                                comment text,
                                commentTs DATETIME,
                                tourneysPlayersId BIGINT UNSIGNED, FOREIGN KEY (tourneysPlayersId) REFERENCES TourneysPlayers(id),

                                wonWhenSeenStreet1 BOOLEAN,
                                wonWhenSeenStreet2 BOOLEAN,
                                wonWhenSeenStreet3 BOOLEAN,
                                wonWhenSeenStreet4 BOOLEAN,
                                wonAtSD BOOLEAN,

                                street0VPIChance BOOLEAN,
                                street0VPI BOOLEAN,
                                street0AggrChance BOOLEAN,
                                street0Aggr BOOLEAN,
                                street0CalledRaiseChance TINYINT,
                                street0CalledRaiseDone TINYINT,
                                street0FaceRaise BOOLEAN,
                                street0_2BChance BOOLEAN,
                                street0_2BDone BOOLEAN,
                                street0_3BChance BOOLEAN,
                                street0_3BDone BOOLEAN,
                                street0_4BChance BOOLEAN,
                                street0_C4BChance BOOLEAN,
                                street0_4BDone BOOLEAN,
                                street0_C4BDone BOOLEAN,
                                street0_FoldTo2BChance BOOLEAN,
                                street0_FoldTo2BDone BOOLEAN,
                                street0_FoldTo3BChance BOOLEAN,
                                street0_FoldTo3BDone BOOLEAN,
                                street0_FoldTo4BChance BOOLEAN,
                                street0_FoldTo4BDone BOOLEAN,
                                street0_SqueezeChance BOOLEAN,
                                street0_SqueezeDone BOOLEAN,

                                raiseToStealChance BOOLEAN,
                                raiseToStealDone BOOLEAN,
                                stealChance BOOLEAN,
                                stealDone BOOLEAN,
                                success_Steal BOOLEAN,

                                street1Seen BOOLEAN,
                                street2Seen BOOLEAN,
                                street3Seen BOOLEAN,
                                street4Seen BOOLEAN,
                                sawShowdown BOOLEAN,
                                showed      BOOLEAN,

                                street0AllIn BOOLEAN,
                                street1AllIn BOOLEAN,
                                street2AllIn BOOLEAN,
                                street3AllIn BOOLEAN,
                                street4AllIn BOOLEAN,
                                wentAllIn BOOLEAN,
                                splashWinnings INT,

                                street0InPosition BOOLEAN,
                                street1InPosition BOOLEAN,
                                street2InPosition BOOLEAN,
                                street3InPosition BOOLEAN,
                                street4InPosition BOOLEAN,
                                street0FirstToAct BOOLEAN,
                                street1FirstToAct BOOLEAN,
                                street2FirstToAct BOOLEAN,
                                street3FirstToAct BOOLEAN,
                                street4FirstToAct BOOLEAN,

                                street1Aggr BOOLEAN,
                                street2Aggr BOOLEAN,
                                street3Aggr BOOLEAN,
                                street4Aggr BOOLEAN,

                                otherRaisedStreet0 BOOLEAN,
                                otherRaisedStreet1 BOOLEAN,
                                otherRaisedStreet2 BOOLEAN,
                                otherRaisedStreet3 BOOLEAN,
                                otherRaisedStreet4 BOOLEAN,
                                foldToOtherRaisedStreet0 BOOLEAN,
                                foldToOtherRaisedStreet1 BOOLEAN,
                                foldToOtherRaisedStreet2 BOOLEAN,
                                foldToOtherRaisedStreet3 BOOLEAN,
                                foldToOtherRaisedStreet4 BOOLEAN,

                                raiseFirstInChance BOOLEAN,
                                raisedFirstIn BOOLEAN,
                                foldBbToStealChance BOOLEAN,
                                foldedBbToSteal BOOLEAN,
                                foldSbToStealChance BOOLEAN,
                                foldedSbToSteal BOOLEAN,

                                street1CBChance BOOLEAN,
                                street1CBDone BOOLEAN,
                                street2CBChance BOOLEAN,
                                street2CBDone BOOLEAN,
                                street2DelayedCBChance BOOLEAN,
                                street2DelayedCBDone BOOLEAN,
                                street2ProbeChance BOOLEAN,
                                street2ProbeDone BOOLEAN,
                                street3CBChance BOOLEAN,
                                street3CBDone BOOLEAN,
                                street4CBChance BOOLEAN,
                                street4CBDone BOOLEAN,

                                foldToStreet1CBChance BOOLEAN,
                                foldToStreet1CBDone BOOLEAN,
                                foldToStreet2CBChance BOOLEAN,
                                foldToStreet2CBDone BOOLEAN,
                                foldToStreet3CBChance BOOLEAN,
                                foldToStreet3CBDone BOOLEAN,
                                foldToStreet4CBChance BOOLEAN,
                                foldToStreet4CBDone BOOLEAN,

                                street1CheckCallRaiseChance BOOLEAN,
                                street1CheckCallDone BOOLEAN,
                                street1CheckRaiseDone BOOLEAN,
                                street2CheckCallRaiseChance BOOLEAN,
                                street2CheckCallDone BOOLEAN,
                                street2CheckRaiseDone BOOLEAN,
                                street3CheckCallRaiseChance BOOLEAN,
                                street3CheckCallDone BOOLEAN,
                                street3CheckRaiseDone BOOLEAN,
                                street4CheckCallRaiseChance BOOLEAN,
                                street4CheckCallDone BOOLEAN,
                                street4CheckRaiseDone BOOLEAN,

                                street0Calls TINYINT,
                                street1Calls TINYINT,
                                street2Calls TINYINT,
                                street3Calls TINYINT,
                                street4Calls TINYINT,
                                street0Bets TINYINT,
                                street1Bets TINYINT,
                                street2Bets TINYINT,
                                street3Bets TINYINT,
                                street4Bets TINYINT,
                                street0Raises TINYINT,
                                street1Raises TINYINT,
                                street2Raises TINYINT,
                                street3Raises TINYINT,
                                street4Raises TINYINT,
        street1Discards TINYINT,
                                 street2Discards TINYINT,
                                 street3Discards TINYINT,
                                 street0Limp BOOLEAN,
                                 street0OpenLimp BOOLEAN,

                                 handString TEXT,
                                actionString VARCHAR(15),
                                cashOutFee BIGINT DEFAULT 0,
                                isCashOut BOOLEAN DEFAULT FALSE,
                                street1_3BChance BOOLEAN,
                                street1_3BDone BOOLEAN,
                                street2_3BChance BOOLEAN,
                                street2_3BDone BOOLEAN,
                                street3_3BChance BOOLEAN,
                                street3_3BDone BOOLEAN,
                                street1_4BChance BOOLEAN,
                                street1_4BDone BOOLEAN,
                                street1_FoldTo4BChance BOOLEAN,
                                street1_FoldTo4BDone BOOLEAN,
                                street2_4BChance BOOLEAN,
                                street2_4BDone BOOLEAN,
                                street2_FoldTo4BChance BOOLEAN,
                                street2_FoldTo4BDone BOOLEAN,
                                street3_4BChance BOOLEAN,
                                street3_4BDone BOOLEAN,
                                street3_FoldTo4BChance BOOLEAN,
                                street3_FoldTo4BDone BOOLEAN,
                                street1OpenChance BOOLEAN,
                                street1OpenDone BOOLEAN,
                                street2OpenChance BOOLEAN,
                                street2OpenDone BOOLEAN,
                                street3OpenChance BOOLEAN,
                                street3OpenDone BOOLEAN,
                                flg_f_fold BOOLEAN,
                                flg_t_fold BOOLEAN,
                                flg_r_fold BOOLEAN,
                                street1FirstRaise BOOLEAN,
                                street2FirstRaise BOOLEAN,
                                street3FirstRaise BOOLEAN,
                                street1FaceRaise BOOLEAN,
                                street2FaceRaise BOOLEAN,
                                street3FaceRaise BOOLEAN,
                                flg_f_donk_def_opp BOOLEAN,
                                flg_t_float_opp BOOLEAN,
                                flg_t_float BOOLEAN,
                                flg_t_float_def_opp BOOLEAN,
                                flg_r_float_opp BOOLEAN,
                                flg_r_float BOOLEAN,
                                flg_r_float_def_opp BOOLEAN,
                                flg_t_donk_def_opp BOOLEAN,
                                flg_r_donk_def_opp BOOLEAN,
                                street1_FoldTo3BChance BOOLEAN,
                                street1_FoldTo3BDone BOOLEAN,
                                street2_FoldTo3BChance BOOLEAN,
                                street2_FoldTo3BDone BOOLEAN,
                                street3_FoldTo3BChance BOOLEAN,
                                street3_FoldTo3BDone BOOLEAN,
                                street0_FoldToSqueezeChance BOOLEAN,
                                street0_FoldToSqueezeDone BOOLEAN,
                                street0_FaceLimpers SMALLINT,
                                cnt_gp_open_opp SMALLINT,
                                cnt_gp_2x SMALLINT,
                                cnt_gp_os SMALLINT,
                                cnt_gp_limp SMALLINT,
                                flg_blind_ds BOOLEAN,
                                flg_blind_db BOOLEAN,
                                flg_blind_k BOOLEAN,
                                flg_faced_allin BOOLEAN,
                                flg_fold_to_allin BOOLEAN,
                                cnt_f_bet_facing INT,
                                val_f_bet_facing_bp INT,
                                cnt_t_bet_facing INT,
                                val_t_bet_facing_bp INT,
                                cnt_r_bet_facing INT,
                                val_r_bet_facing_bp INT,
                                cnt_p_2bet_facing INT,
                                val_p_2bet_facing_bp INT,
                                cnt_p_3bet_facing INT,
                                val_p_3bet_facing_bp INT,
                                cnt_p_4bet_facing INT,
                                val_p_4bet_facing_bp INT,
                                cnt_f_bet_made INT,
                                val_f_bet_made_bp INT,
                                cnt_t_bet_made INT,
                                val_t_bet_made_bp INT,
                                cnt_r_bet_made INT,
                                val_r_bet_made_bp INT,
                                cnt_f_spr INT,
                                val_f_spr INT,
                                cnt_t_spr INT,
                                val_t_spr INT,
                                cnt_r_spr INT,
                                val_r_spr INT,
                                cnt_p_raise_made INT,
                                val_p_raise_made_bp INT,
                                cnt_f_raise_made INT,
                                val_f_raise_made_bp INT,
                                cnt_t_raise_made INT,
                                val_t_raise_made_bp INT,
                                cnt_r_raise_made INT,
                                val_r_raise_made_bp INT,
                                cnt_f_2bet_facing INT,
                                val_f_2bet_facing_bp INT,
                                cnt_f_3bet_facing INT,
                                val_f_3bet_facing_bp INT,
                                cnt_f_4bet_facing INT,
                                val_f_4bet_facing_bp INT,
                                cnt_t_2bet_facing INT,
                                val_t_2bet_facing_bp INT,
                                cnt_t_3bet_facing INT,
                                val_t_3bet_facing_bp INT,
                                cnt_t_4bet_facing INT,
                                val_t_4bet_facing_bp INT,
                                cnt_r_2bet_facing INT,
                                val_r_2bet_facing_bp INT,
                                cnt_r_3bet_facing INT,
                                val_r_3bet_facing_bp INT,
                                cnt_r_4bet_facing INT,
                                val_r_4bet_facing_bp INT,
                                amt_blind INT,
                                amt_bet_p INT,
                                amt_bet_f INT,
                                amt_bet_t INT,
                                amt_bet_r INT,
                                amt_bet_ttl INT,
                                cnt_p_raise_facing INT,
                                val_p_raise_facing_bp INT,
                                cnt_f_raise_facing INT,
                                val_f_raise_facing_bp INT,
                                cnt_t_raise_facing INT,
                                val_t_raise_facing_bp INT,
                                cnt_r_raise_facing INT,
                                val_r_raise_facing_bp INT,
                                cnt_p_raise_made_2 INT,
                                val_p_raise_made_2_bp INT,
                                cnt_f_raise_made_2 INT,
                                val_f_raise_made_2_bp INT,
                                cnt_t_raise_made_2 INT,
                                val_t_raise_made_2_bp INT,
                                cnt_r_raise_made_2 INT,
                                val_r_raise_made_2_bp INT,
                                cnt_p_5bet_facing INT,
                                val_p_5bet_facing_bp INT)
                                ENGINE=INNODB"""
    elif db_server == "postgresql":
        ddl = """CREATE TABLE HandsPlayers (
                                id BIGSERIAL, PRIMARY KEY (id),
                                handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                                playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                                startCash BIGINT NOT NULL,
                                effStack BIGINT NOT NULL,
                                startBounty BIGINT,
                                endBounty BIGINT,
                                position CHAR(1),
                                seatNo SMALLINT NOT NULL,
                                sitout BOOLEAN NOT NULL,

                                card1 smallint NOT NULL,  /* 0=none, 1-13=2-Ah 14-26=2-Ad 27-39=2-Ac 40-52=2-As */
                                card2 smallint NOT NULL,
                                card3 smallint,
                                card4 smallint,
                                card5 smallint,
                                card6 smallint,
                                card7 smallint,
                                card8 smallint,  /* cards 8-20 for draw hands */
                                card9 smallint,
                                card10 smallint,
                                card11 smallint,
                                card12 smallint,
                                card13 smallint,
                                card14 smallint,
                                card15 smallint,
                                card16 smallint,
                                card17 smallint,
                                card18 smallint,
                                card19 smallint,
                                card20 smallint,
                                startCards smallint, FOREIGN KEY (startCards) REFERENCES StartCards(id),

                                common BIGINT NOT NULL,
                                committed BIGINT NOT NULL,
                                winnings BIGINT NOT NULL,
                                rake BIGINT NOT NULL,
                                rakeDealt NUMERIC NOT NULL,
                                rakeContributed NUMERIC NOT NULL,
                                rakeWeighted NUMERIC NOT NULL,
                                totalProfit BIGINT,
                                allInEV NUMERIC,
                                comment text,
                                commentTs timestamp without time zone,
                                tourneysPlayersId BIGINT, FOREIGN KEY (tourneysPlayersId) REFERENCES TourneysPlayers(id),

                                wonWhenSeenStreet1 BOOLEAN,
                                wonWhenSeenStreet2 BOOLEAN,
                                wonWhenSeenStreet3 BOOLEAN,
                                wonWhenSeenStreet4 BOOLEAN,
                                wonAtSD BOOLEAN,

                                street0VPIChance BOOLEAN,
                                street0VPI BOOLEAN,
                                street0AggrChance BOOLEAN,
                                street0Aggr BOOLEAN,
                                street0CalledRaiseChance SMALLINT,
                                street0CalledRaiseDone SMALLINT,
                                street0FaceRaise BOOLEAN,
                                street0_2BChance BOOLEAN,
                                street0_2BDone BOOLEAN,
                                street0_3BChance BOOLEAN,
                                street0_3BDone BOOLEAN,
                                street0_4BChance BOOLEAN,
                                street0_4BDone BOOLEAN,
                                street0_C4BChance BOOLEAN,
                                street0_C4BDone BOOLEAN,
                                street0_FoldTo2BChance BOOLEAN,
                                street0_FoldTo2BDone BOOLEAN,
                                street0_FoldTo3BChance BOOLEAN,
                                street0_FoldTo3BDone BOOLEAN,
                                street0_FoldTo4BChance BOOLEAN,
                                street0_FoldTo4BDone BOOLEAN,
                                street0_SqueezeChance BOOLEAN,
                                street0_SqueezeDone BOOLEAN,

                                raiseToStealChance BOOLEAN,
                                raiseToStealDone BOOLEAN,
                                stealChance BOOLEAN,
                                stealDone BOOLEAN,
                                success_Steal BOOLEAN,

                                street1Seen BOOLEAN,
                                street2Seen BOOLEAN,
                                street3Seen BOOLEAN,
                                street4Seen BOOLEAN,
                                sawShowdown BOOLEAN,
                                showed      BOOLEAN,

                                street0AllIn BOOLEAN,
                                street1AllIn BOOLEAN,
                                street2AllIn BOOLEAN,
                                street3AllIn BOOLEAN,
                                street4AllIn BOOLEAN,
                                wentAllIn BOOLEAN,
                                splashWinnings INT,

                                street0InPosition BOOLEAN,
                                street1InPosition BOOLEAN,
                                street2InPosition BOOLEAN,
                                street3InPosition BOOLEAN,
                                street4InPosition BOOLEAN,
                                street0FirstToAct BOOLEAN,
                                street1FirstToAct BOOLEAN,
                                street2FirstToAct BOOLEAN,
                                street3FirstToAct BOOLEAN,
                                street4FirstToAct BOOLEAN,

                                street1Aggr BOOLEAN,
                                street2Aggr BOOLEAN,
                                street3Aggr BOOLEAN,
                                street4Aggr BOOLEAN,

                                otherRaisedStreet0 BOOLEAN,
                                otherRaisedStreet1 BOOLEAN,
                                otherRaisedStreet2 BOOLEAN,
                                otherRaisedStreet3 BOOLEAN,
                                otherRaisedStreet4 BOOLEAN,
                                foldToOtherRaisedStreet0 BOOLEAN,
                                foldToOtherRaisedStreet1 BOOLEAN,
                                foldToOtherRaisedStreet2 BOOLEAN,
                                foldToOtherRaisedStreet3 BOOLEAN,
                                foldToOtherRaisedStreet4 BOOLEAN,

                                raiseFirstInChance BOOLEAN,
                                raisedFirstIn BOOLEAN,
                                foldBbToStealChance BOOLEAN,
                                foldedBbToSteal BOOLEAN,
                                foldSbToStealChance BOOLEAN,
                                foldedSbToSteal BOOLEAN,

                                street1CBChance BOOLEAN,
                                street1CBDone BOOLEAN,
                                street2CBChance BOOLEAN,
                                street2CBDone BOOLEAN,
                                street2DelayedCBChance BOOLEAN,
                                street2DelayedCBDone BOOLEAN,
                                street2ProbeChance BOOLEAN,
                                street2ProbeDone BOOLEAN,
                                street3CBChance BOOLEAN,
                                street3CBDone BOOLEAN,
                                street4CBChance BOOLEAN,
                                street4CBDone BOOLEAN,

                                foldToStreet1CBChance BOOLEAN,
                                foldToStreet1CBDone BOOLEAN,
                                foldToStreet2CBChance BOOLEAN,
                                foldToStreet2CBDone BOOLEAN,
                                foldToStreet3CBChance BOOLEAN,
                                foldToStreet3CBDone BOOLEAN,
                                foldToStreet4CBChance BOOLEAN,
                                foldToStreet4CBDone BOOLEAN,

                                street1CheckCallRaiseChance BOOLEAN,
                                street1CheckCallDone BOOLEAN,
                                street1CheckRaiseDone BOOLEAN,
                                street2CheckCallRaiseChance BOOLEAN,
                                street2CheckCallDone BOOLEAN,
                                street2CheckRaiseDone BOOLEAN,
                                street3CheckCallRaiseChance BOOLEAN,
                                street3CheckCallDone BOOLEAN,
                                street3CheckRaiseDone BOOLEAN,
                                street4CheckCallRaiseChance BOOLEAN,
                                street4CheckCallDone BOOLEAN,
                                street4CheckRaiseDone BOOLEAN,

                                street0Calls SMALLINT,
                                street1Calls SMALLINT,
                                street2Calls SMALLINT,
                                street3Calls SMALLINT,
                                street4Calls SMALLINT,
                                street0Bets SMALLINT,
                                street1Bets SMALLINT,
                                street2Bets SMALLINT,
                                street3Bets SMALLINT,
                                street4Bets SMALLINT,
                                street0Raises SMALLINT,
                                street1Raises SMALLINT,
                                street2Raises SMALLINT,
                                street3Raises SMALLINT,
                                street4Raises SMALLINT,
                                street1Discards SMALLINT,
                                street2Discards SMALLINT,
        street3Discards SMALLINT,
                                 street0Limp BOOLEAN,
                                 street0OpenLimp BOOLEAN,

                                 handString TEXT,
                                actionString VARCHAR(15),
                                cashOutFee BIGINT DEFAULT 0,
                                isCashOut BOOLEAN DEFAULT FALSE,
                                street1_3BChance BOOLEAN,
                                street1_3BDone BOOLEAN,
                                street2_3BChance BOOLEAN,
                                street2_3BDone BOOLEAN,
                                street3_3BChance BOOLEAN,
                                street3_3BDone BOOLEAN,
                                street1_4BChance BOOLEAN,
                                street1_4BDone BOOLEAN,
                                street1_FoldTo4BChance BOOLEAN,
                                street1_FoldTo4BDone BOOLEAN,
                                street2_4BChance BOOLEAN,
                                street2_4BDone BOOLEAN,
                                street2_FoldTo4BChance BOOLEAN,
                                street2_FoldTo4BDone BOOLEAN,
                                street3_4BChance BOOLEAN,
                                street3_4BDone BOOLEAN,
                                street3_FoldTo4BChance BOOLEAN,
                                street3_FoldTo4BDone BOOLEAN,
                                street1OpenChance BOOLEAN,
                                street1OpenDone BOOLEAN,
                                street2OpenChance BOOLEAN,
                                street2OpenDone BOOLEAN,
                                street3OpenChance BOOLEAN,
                                street3OpenDone BOOLEAN,
                                flg_f_fold BOOLEAN,
                                flg_t_fold BOOLEAN,
                                flg_r_fold BOOLEAN,
                                street1FirstRaise BOOLEAN,
                                street2FirstRaise BOOLEAN,
                                street3FirstRaise BOOLEAN,
                                street1FaceRaise BOOLEAN,
                                street2FaceRaise BOOLEAN,
                                street3FaceRaise BOOLEAN,
                                flg_f_donk_def_opp BOOLEAN,
                                flg_t_float_opp BOOLEAN,
                                flg_t_float BOOLEAN,
                                flg_t_float_def_opp BOOLEAN,
                                flg_r_float_opp BOOLEAN,
                                flg_r_float BOOLEAN,
                                flg_r_float_def_opp BOOLEAN,
                                flg_t_donk_def_opp BOOLEAN,
                                flg_r_donk_def_opp BOOLEAN,
                                street1_FoldTo3BChance BOOLEAN,
                                street1_FoldTo3BDone BOOLEAN,
                                street2_FoldTo3BChance BOOLEAN,
                                street2_FoldTo3BDone BOOLEAN,
                                street3_FoldTo3BChance BOOLEAN,
                                street3_FoldTo3BDone BOOLEAN,
                                street0_FoldToSqueezeChance BOOLEAN,
                                street0_FoldToSqueezeDone BOOLEAN,
                                street0_FaceLimpers SMALLINT,
                                cnt_gp_open_opp SMALLINT,
                                cnt_gp_2x SMALLINT,
                                cnt_gp_os SMALLINT,
                                cnt_gp_limp SMALLINT,
                                flg_blind_ds BOOLEAN,
                                flg_blind_db BOOLEAN,
                                flg_blind_k BOOLEAN,
                                flg_faced_allin BOOLEAN,
                                flg_fold_to_allin BOOLEAN,
                                cnt_f_bet_facing INT,
                                val_f_bet_facing_bp INT,
                                cnt_t_bet_facing INT,
                                val_t_bet_facing_bp INT,
                                cnt_r_bet_facing INT,
                                val_r_bet_facing_bp INT,
                                cnt_p_2bet_facing INT,
                                val_p_2bet_facing_bp INT,
                                cnt_p_3bet_facing INT,
                                val_p_3bet_facing_bp INT,
                                cnt_p_4bet_facing INT,
                                val_p_4bet_facing_bp INT,
                                cnt_f_bet_made INT,
                                val_f_bet_made_bp INT,
                                cnt_t_bet_made INT,
                                val_t_bet_made_bp INT,
                                cnt_r_bet_made INT,
                                val_r_bet_made_bp INT,
                                cnt_f_spr INT,
                                val_f_spr INT,
                                cnt_t_spr INT,
                                val_t_spr INT,
                                cnt_r_spr INT,
                                val_r_spr INT,
                                cnt_p_raise_made INT,
                                val_p_raise_made_bp INT,
                                cnt_f_raise_made INT,
                                val_f_raise_made_bp INT,
                                cnt_t_raise_made INT,
                                val_t_raise_made_bp INT,
                                cnt_r_raise_made INT,
                                val_r_raise_made_bp INT,
                                cnt_f_2bet_facing INT,
                                val_f_2bet_facing_bp INT,
                                cnt_f_3bet_facing INT,
                                val_f_3bet_facing_bp INT,
                                cnt_f_4bet_facing INT,
                                val_f_4bet_facing_bp INT,
                                cnt_t_2bet_facing INT,
                                val_t_2bet_facing_bp INT,
                                cnt_t_3bet_facing INT,
                                val_t_3bet_facing_bp INT,
                                cnt_t_4bet_facing INT,
                                val_t_4bet_facing_bp INT,
                                cnt_r_2bet_facing INT,
                                val_r_2bet_facing_bp INT,
                                cnt_r_3bet_facing INT,
                                val_r_3bet_facing_bp INT,
                                cnt_r_4bet_facing INT,
                                val_r_4bet_facing_bp INT,
                                amt_blind INT,
                                amt_bet_p INT,
                                amt_bet_f INT,
                                amt_bet_t INT,
                                amt_bet_r INT,
                                amt_bet_ttl INT,
                                cnt_p_raise_facing INT,
                                val_p_raise_facing_bp INT,
                                cnt_f_raise_facing INT,
                                val_f_raise_facing_bp INT,
                                cnt_t_raise_facing INT,
                                val_t_raise_facing_bp INT,
                                cnt_r_raise_facing INT,
                                val_r_raise_facing_bp INT,
                                cnt_p_raise_made_2 INT,
                                val_p_raise_made_2_bp INT,
                                cnt_f_raise_made_2 INT,
                                val_f_raise_made_2_bp INT,
                                cnt_t_raise_made_2 INT,
                                val_t_raise_made_2_bp INT,
                                cnt_r_raise_made_2 INT,
                                val_r_raise_made_2_bp INT,
                                cnt_p_5bet_facing INT,
                                val_p_5bet_facing_bp INT)"""
    elif db_server == "sqlite":
        ddl = """CREATE TABLE HandsPlayers (
                                id INTEGER PRIMARY KEY,
                                handId INT NOT NULL,
                                playerId INT NOT NULL,
                                startCash INT NOT NULL,
                                effStack INT NOT NULL,
                                startBounty INT,
                                endBounty INT,
                                position TEXT,
                                seatNo INT NOT NULL,
                                sitout BOOLEAN NOT NULL,

                                card1 INT NOT NULL,  /* 0=none, 1-13=2-Ah 14-26=2-Ad 27-39=2-Ac 40-52=2-As */
                                card2 INT NOT NULL,
                                card3 INT,
                                card4 INT,
                                card5 INT,
                                card6 INT,
                                card7 INT,
                                card8 INT,  /* cards 8-20 for draw hands */
                                card9 INT,
                                card10 INT,
                                card11 INT,
                                card12 INT,
                                card13 INT,
                                card14 INT,
                                card15 INT,
                                card16 INT,
                                card17 INT,
                                card18 INT,
                                card19 INT,
                                card20 INT,
                                startCards INT,

                                common INT NOT NULL,
                                committed INT NOT NULL,
                                winnings INT NOT NULL,
                                rake INT NOT NULL,
                                rakeDealt decimal NOT NULL,
                                rakeContributed decimal NOT NULL,
                                rakeWeighted decimal NOT NULL,
                                totalProfit INT,
                                allInEV decimal,
                                comment TEXT,
                                commentTs timestamp,
                                tourneysPlayersId INT,

                                wonWhenSeenStreet1 INT,
                                wonWhenSeenStreet2 INT,
                                wonWhenSeenStreet3 INT,
                                wonWhenSeenStreet4 INT,
                                wonAtSD INT,

                                street0VPIChance INT,
                                street0VPI INT,
                                street0AggrChance INT,
                                street0Aggr INT,
                                street0CalledRaiseChance INT,
                                street0CalledRaiseDone INT,
                                street0FaceRaise INT,
                                street0_2BChance INT,
                                street0_2BDone INT,
                                street0_3BChance INT,
                                street0_3BDone INT,
                                street0_4BChance INT,
                                street0_4BDone INT,
                                street0_C4BChance INT,
                                street0_C4BDone INT,
                                street0_FoldTo2BChance INT,
                                street0_FoldTo2BDone INT,
                                street0_FoldTo3BChance INT,
                                street0_FoldTo3BDone INT,
                                street0_FoldTo4BChance INT,
                                street0_FoldTo4BDone INT,
                                street0_SqueezeChance INT,
                                street0_SqueezeDone INT,

                                raiseToStealChance INT,
                                raiseToStealDone INT,
                                stealChance INT,
                                stealDone INT,
                                success_Steal INT,

                                street1Seen INT,
                                street2Seen INT,
                                street3Seen INT,
                                street4Seen INT,
                                sawShowdown INT,
                                showed      INT,

                                street0AllIn INT,
                                street1AllIn INT,
                                street2AllIn INT,
                                street3AllIn INT,
                                street4AllIn INT,
                                wentAllIn INT,
                                splashWinnings INT,

                                street0InPosition INT,
                                street1InPosition INT,
                                street2InPosition INT,
                                street3InPosition INT,
                                street4InPosition INT,
                                street0FirstToAct INT,
                                street1FirstToAct INT,
                                street2FirstToAct INT,
                                street3FirstToAct INT,
                                street4FirstToAct INT,

                                street1Aggr INT,
                                street2Aggr INT,
                                street3Aggr INT,
                                street4Aggr INT,

                                otherRaisedStreet0 INT,
                                otherRaisedStreet1 INT,
                                otherRaisedStreet2 INT,
                                otherRaisedStreet3 INT,
                                otherRaisedStreet4 INT,
                                foldToOtherRaisedStreet0 INT,
                                foldToOtherRaisedStreet1 INT,
                                foldToOtherRaisedStreet2 INT,
                                foldToOtherRaisedStreet3 INT,
                                foldToOtherRaisedStreet4 INT,

                                raiseFirstInChance INT,
                                raisedFirstIn INT,
                                foldBbToStealChance INT,
                                foldedBbToSteal INT,
                                foldSbToStealChance INT,
                                foldedSbToSteal INT,

                                street1CBChance INT,
                                street1CBDone INT,
                                street2CBChance INT,
                                street2CBDone INT,
                                street3CBChance INT,
                                street3CBDone INT,
                                street4CBChance INT,
                                street4CBDone INT,
                                street2DelayedCBChance INT,
                                street2DelayedCBDone INT,
                                street2ProbeChance INT,
                                street2ProbeDone INT,

                                foldToStreet1CBChance INT,
                                foldToStreet1CBDone INT,
                                foldToStreet2CBChance INT,
                                foldToStreet2CBDone INT,
                                foldToStreet3CBChance INT,
                                foldToStreet3CBDone INT,
                                foldToStreet4CBChance INT,
                                foldToStreet4CBDone INT,

                                street1CheckCallRaiseChance INT,
                                street1CheckCallDone INT,
                                street1CheckRaiseDone INT,
                                street2CheckCallRaiseChance INT,
                                street2CheckCallDone INT,
                                street2CheckRaiseDone INT,
                                street3CheckCallRaiseChance INT,
                                street3CheckCallDone INT,
                                street3CheckRaiseDone INT,
                                street4CheckCallRaiseChance INT,
                                street4CheckCallDone INT,
                                street4CheckRaiseDone INT,

                                street0Calls INT,
                                street1Calls INT,
                                street2Calls INT,
                                street3Calls INT,
                                street4Calls INT,
                                street0Bets INT,
                                street1Bets INT,
                                street2Bets INT,
                                street3Bets INT,
                                street4Bets INT,
                                street0Raises INT,
                                street1Raises INT,
                                street2Raises INT,
                                street3Raises INT,
        street4Raises INT,
                                 street1Discards INT,
                                 street2Discards INT,
                                 street3Discards INT,

                                 handString TEXT,
                                 street0Limp INT,
                                 street0OpenLimp INT,
                                 actionString VARCHAR(15),
                                 cashOutFee INT DEFAULT 0,
                                isCashOut BOOLEAN DEFAULT 0,
                                street1_3BChance INT,
                                street1_3BDone INT,
                                street2_3BChance INT,
                                street2_3BDone INT,
                                street3_3BChance INT,
                                street3_3BDone INT,
                                  street1_4BChance INT,
                                  street1_4BDone INT,
                                  street1_FoldTo4BChance INT,
                                  street1_FoldTo4BDone INT,
                                  street2_4BChance INT,
                                  street2_4BDone INT,
                                  street2_FoldTo4BChance INT,
                                  street2_FoldTo4BDone INT,
                                  street3_4BChance INT,
                                  street3_4BDone INT,
                                  street3_FoldTo4BChance INT,
                                  street3_FoldTo4BDone INT,
                                  street1OpenChance INT,
                                  street1OpenDone INT,
                                  street2OpenChance INT,
                                  street2OpenDone INT,
                                  street3OpenChance INT,
                                  street3OpenDone INT,
                                  flg_f_fold INT,
                                  flg_t_fold INT,
                                  flg_r_fold INT,
                                  street1FirstRaise INT,
                                  street2FirstRaise INT,
                                  street3FirstRaise INT,
                                  street1FaceRaise INT,
                                  street2FaceRaise INT,
                                  street3FaceRaise INT,
                                  flg_f_donk_def_opp INT,
                                  flg_t_float_opp INT,
                                  flg_t_float INT,
                                  flg_t_float_def_opp INT,
                                  flg_r_float_opp INT,
                                  flg_r_float INT,
                                  flg_r_float_def_opp INT,
                                  flg_t_donk_def_opp INT,
                                  flg_r_donk_def_opp INT,
                                  street1_FoldTo3BChance INT,
                                  street1_FoldTo3BDone INT,
                                  street2_FoldTo3BChance INT,
                                  street2_FoldTo3BDone INT,
                                  street3_FoldTo3BChance INT,
                                  street3_FoldTo3BDone INT,
                                  street0_FoldToSqueezeChance INT,
                                  street0_FoldToSqueezeDone INT,
                                  street0_FaceLimpers INT,
                                  cnt_gp_open_opp INT,
                                  cnt_gp_2x INT,
                                  cnt_gp_os INT,
                                  cnt_gp_limp INT,
                                  flg_blind_ds INT,
                                  flg_blind_db INT,
                                  flg_blind_k INT,
                                  flg_faced_allin INT,
                                  flg_fold_to_allin INT,
                                  cnt_f_bet_facing INT,
                                  val_f_bet_facing_bp INT,
                                  cnt_t_bet_facing INT,
                                  val_t_bet_facing_bp INT,
                                  cnt_r_bet_facing INT,
                                  val_r_bet_facing_bp INT,
                                  cnt_p_2bet_facing INT,
                                  val_p_2bet_facing_bp INT,
                                  cnt_p_3bet_facing INT,
                                  val_p_3bet_facing_bp INT,
                                  cnt_p_4bet_facing INT,
                                  val_p_4bet_facing_bp INT,
                                  cnt_f_bet_made INT,
                                  val_f_bet_made_bp INT,
                                  cnt_t_bet_made INT,
                                  val_t_bet_made_bp INT,
                                  cnt_r_bet_made INT,
                                  val_r_bet_made_bp INT,
                                  cnt_f_spr INT,
                                  val_f_spr INT,
                                  cnt_t_spr INT,
                                  val_t_spr INT,
                                  cnt_r_spr INT,
                                  val_r_spr INT,
                                  cnt_p_raise_made INT,
                                  val_p_raise_made_bp INT,
                                  cnt_f_raise_made INT,
                                  val_f_raise_made_bp INT,
                                  cnt_t_raise_made INT,
                                  val_t_raise_made_bp INT,
                                  cnt_r_raise_made INT,
                                  val_r_raise_made_bp INT,
                                  cnt_f_2bet_facing INT,
                                  val_f_2bet_facing_bp INT,
                                  cnt_f_3bet_facing INT,
                                  val_f_3bet_facing_bp INT,
                                  cnt_f_4bet_facing INT,
                                  val_f_4bet_facing_bp INT,
                                  cnt_t_2bet_facing INT,
                                  val_t_2bet_facing_bp INT,
                                  cnt_t_3bet_facing INT,
                                  val_t_3bet_facing_bp INT,
                                  cnt_t_4bet_facing INT,
                                  val_t_4bet_facing_bp INT,
                                  cnt_r_2bet_facing INT,
                                  val_r_2bet_facing_bp INT,
                                  cnt_r_3bet_facing INT,
                                  val_r_3bet_facing_bp INT,
                                  cnt_r_4bet_facing INT,
                                  val_r_4bet_facing_bp INT,
                                  amt_blind INT,
                                  amt_bet_p INT,
                                  amt_bet_f INT,
                                  amt_bet_t INT,
                                  amt_bet_r INT,
                                  amt_bet_ttl INT,
                                  cnt_p_raise_facing INT,
                                  val_p_raise_facing_bp INT,
                                  cnt_f_raise_facing INT,
                                  val_f_raise_facing_bp INT,
                                  cnt_t_raise_facing INT,
                                  val_t_raise_facing_bp INT,
                                  cnt_r_raise_facing INT,
                                  val_r_raise_facing_bp INT,
                                  cnt_p_raise_made_2 INT,
                                  val_p_raise_made_2_bp INT,
                                  cnt_f_raise_made_2 INT,
                                  val_f_raise_made_2_bp INT,
                                  cnt_t_raise_made_2 INT,
                                  val_t_raise_made_2_bp INT,
                                  cnt_r_raise_made_2 INT,
                                  val_r_raise_made_2_bp INT,
                                  cnt_p_5bet_facing INT,
                                  val_p_5bet_facing_bp INT)
                                """
    else:
        return {}
    return {"createHandsPlayersTable": ddl}

