"""Poker hand-domain schema queries."""

from __future__ import annotations


def hand_schema_queries(db_server: str) -> dict[str, str]:
    """Return backend-specific DDL for hand-domain tables."""
    if db_server == "mysql":
        return {
            "createHandsActionsTable": """CREATE TABLE HandsActions (
                        id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        street SMALLINT NOT NULL,
                        actionNo SMALLINT NOT NULL,
                        streetActionNo SMALLINT NOT NULL,
                        actionId SMALLINT UNSIGNED NOT NULL, FOREIGN KEY (actionId) REFERENCES Actions(id),
                        amount BIGINT NOT NULL,
                        raiseTo BIGINT NOT NULL,
                        amountCalled BIGINT NOT NULL,
                        numDiscarded SMALLINT NOT NULL,
                        cardsDiscarded varchar(14),
                        allIn BOOLEAN NOT NULL,
                        actionType varchar(24),
                        toCall BIGINT NOT NULL DEFAULT 0,
                        potBefore BIGINT NOT NULL DEFAULT 0,
                        potAfter BIGINT NOT NULL DEFAULT 0,
                        sizingBp INT NOT NULL DEFAULT 0,
                        position SMALLINT,
                        relativePosition SMALLINT NOT NULL DEFAULT 0,
                        inPosition BOOLEAN NOT NULL DEFAULT false,
                        effectiveStack BIGINT NOT NULL DEFAULT 0,
                        effectiveStackBB INT NOT NULL DEFAULT 0,
                        sprBefore INT NOT NULL DEFAULT 0,
                        isAggressor BOOLEAN NOT NULL DEFAULT false,
                        facingActionType varchar(24),
                        facingAmount BIGINT NOT NULL DEFAULT 0,
                        facingSizingBp INT NOT NULL DEFAULT 0,
                        raiserCount SMALLINT NOT NULL DEFAULT 0,
                        callerCount SMALLINT NOT NULL DEFAULT 0,
                        playersInHand SMALLINT NOT NULL DEFAULT 0)
                        ENGINE=INNODB""",
            "createBoardsTable": """CREATE TABLE Boards (
                            id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                            handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                            boardId smallint,
                            boardcard1 smallint,  /* 0=none, 1-13=2-Ah 14-26=2-Ad 27-39=2-Ac 40-52=2-As */
                            boardcard2 smallint,
                            boardcard3 smallint,
                            boardcard4 smallint,
                            boardcard5 smallint)
                        ENGINE=INNODB""",
            "createBoardFeaturesTable": """CREATE TABLE BoardFeatures (
                            id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                            handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                            boardId SMALLINT NOT NULL DEFAULT 1,
                            street SMALLINT NOT NULL,
                            streetName VARCHAR(12) NOT NULL DEFAULT '',
                            cardCount SMALLINT NOT NULL DEFAULT 0,
                            textureMask INT NOT NULL DEFAULT 0,
                            runoutMask INT NOT NULL DEFAULT 0,
                            topRank SMALLINT NOT NULL DEFAULT 0,
                            suitStructure VARCHAR(12) NOT NULL DEFAULT '',
                            pairing VARCHAR(12) NOT NULL DEFAULT '',
                            rankBucket VARCHAR(12) NOT NULL DEFAULT '',
                            connectivity VARCHAR(16) NOT NULL DEFAULT '')
                        ENGINE=INNODB""",
            "createHandsCashoutTable": """CREATE TABLE HandsCashout (
                        id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        amount NUMERIC,
                        fee NUMERIC)
                        ENGINE=INNODB""",
            "createHandsShowdownTable": """CREATE TABLE HandsShowdown (
                        id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        combo VARCHAR(255),
                        cards VARCHAR(64))
                        ENGINE=INNODB""",
            "createHandsStoveTable": """CREATE TABLE HandsStove (
                        id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        streetId SMALLINT,
                        boardId SMALLINT,
                        hiLo char(1) NOT NULL,
                        rankId SMALLINT UNSIGNED NOT NULL, FOREIGN KEY (rankId) REFERENCES `Rank`(id),
                        value BIGINT,
                        cards VARCHAR(5),
                        ev NUMERIC)
                        ENGINE=INNODB""",
            "createHandsPotsTable": """CREATE TABLE HandsPots (
                        id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY (id),
                        handId BIGINT UNSIGNED NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        potId SMALLINT,
                        boardId SMALLINT,
                        hiLo char(1) NOT NULL,
                        playerId INT UNSIGNED NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        pot BIGINT,
                        collected BIGINT,
                        rake INT)
                        ENGINE=INNODB""",
        }
    if db_server == "postgresql":
        return {
            "createHandsActionsTable": """CREATE TABLE HandsActions (
                        id BIGSERIAL, PRIMARY KEY (id),
                        handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        street SMALLINT,
                        actionNo SMALLINT,
                        streetActionNo SMALLINT,
                        actionId SMALLINT, FOREIGN KEY (actionId) REFERENCES Actions(id),
                        amount BIGINT,
                        raiseTo BIGINT,
                        amountCalled BIGINT,
                        numDiscarded SMALLINT,
                        cardsDiscarded varchar(14),
                        allIn BOOLEAN,
                        actionType varchar(24),
                        toCall BIGINT DEFAULT 0,
                        potBefore BIGINT DEFAULT 0,
                        potAfter BIGINT DEFAULT 0,
                        sizingBp INT DEFAULT 0,
                        position SMALLINT,
                        relativePosition SMALLINT DEFAULT 0,
                        inPosition BOOLEAN DEFAULT false,
                        effectiveStack BIGINT DEFAULT 0,
                        effectiveStackBB INT DEFAULT 0,
                        sprBefore INT DEFAULT 0,
                        isAggressor BOOLEAN DEFAULT false,
                        facingActionType varchar(24),
                        facingAmount BIGINT DEFAULT 0,
                        facingSizingBp INT DEFAULT 0,
                        raiserCount SMALLINT DEFAULT 0,
                        callerCount SMALLINT DEFAULT 0,
                        playersInHand SMALLINT DEFAULT 0)""",
            "createBoardsTable": """CREATE TABLE Boards (
                            id BIGSERIAL, PRIMARY KEY (id),
                            handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                            boardId smallint,
                            boardcard1 smallint,  /* 0=none, 1-13=2-Ah 14-26=2-Ad 27-39=2-Ac 40-52=2-As */
                            boardcard2 smallint,
                            boardcard3 smallint,
                            boardcard4 smallint,
                            boardcard5 smallint)""",
            "createBoardFeaturesTable": """CREATE TABLE BoardFeatures (
                            id BIGSERIAL, PRIMARY KEY (id),
                            handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                            boardId SMALLINT NOT NULL DEFAULT 1,
                            street SMALLINT NOT NULL,
                            streetName VARCHAR(12) NOT NULL DEFAULT '',
                            cardCount SMALLINT NOT NULL DEFAULT 0,
                            textureMask INT NOT NULL DEFAULT 0,
                            runoutMask INT NOT NULL DEFAULT 0,
                            topRank SMALLINT NOT NULL DEFAULT 0,
                            suitStructure VARCHAR(12) NOT NULL DEFAULT '',
                            pairing VARCHAR(12) NOT NULL DEFAULT '',
                            rankBucket VARCHAR(12) NOT NULL DEFAULT '',
                            connectivity VARCHAR(16) NOT NULL DEFAULT '')""",
            "createHandsCashoutTable": """CREATE TABLE HandsCashout (
                        id BIGSERIAL, PRIMARY KEY (id),
                        handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        amount NUMERIC,
                        fee NUMERIC)""",
            "createHandsShowdownTable": """CREATE TABLE HandsShowdown (
                        id BIGSERIAL, PRIMARY KEY (id),
                        handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        combo VARCHAR(255),
                        cards VARCHAR(64))""",
            "createHandsStoveTable": """CREATE TABLE HandsStove (
                        id BIGSERIAL, PRIMARY KEY (id),
                        handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        streetId SMALLINT,
                        boardId SMALLINT,
                        hiLo char(1) NOT NULL,
                        rankId SMALLINT NOT NULL, FOREIGN KEY (rankId) REFERENCES Rank(id),
                        value BIGINT,
                        cards VARCHAR(5),
                        ev NUMERIC)""",
            "createHandsPotsTable": """CREATE TABLE HandsPots (
                        id BIGSERIAL, PRIMARY KEY (id),
                        handId BIGINT NOT NULL, FOREIGN KEY (handId) REFERENCES Hands(id),
                        potId SMALLINT,
                        boardId SMALLINT,
                        hiLo char(1) NOT NULL,
                        playerId INT NOT NULL, FOREIGN KEY (playerId) REFERENCES Players(id),
                        pot BIGINT,
                        collected BIGINT,
                        rake INT)""",
        }
    if db_server == "sqlite":
        return {
            "createHandsActionsTable": """CREATE TABLE HandsActions (
                        id INTEGER PRIMARY KEY,
                        handId INT NOT NULL,
                        playerId INT NOT NULL,
                        street SMALLINT,
                        actionNo SMALLINT,
                        streetActionNo SMALLINT,
                        actionId SMALLINT,
                        amount INT,
                        raiseTo INT,
                        amountCalled INT,
                        numDiscarded SMALLINT,
                        cardsDiscarded TEXT,
                        allIn BOOLEAN,
                        actionType VARCHAR(24),
                        toCall BIGINT DEFAULT 0,
                        potBefore BIGINT DEFAULT 0,
                        potAfter BIGINT DEFAULT 0,
                        sizingBp INT DEFAULT 0,
                        position SMALLINT,
                        relativePosition SMALLINT DEFAULT 0,
                        inPosition BOOLEAN DEFAULT false,
                        effectiveStack BIGINT DEFAULT 0,
                        effectiveStackBB INT DEFAULT 0,
                        sprBefore INT DEFAULT 0,
                        isAggressor BOOLEAN DEFAULT false,
                        facingActionType VARCHAR(24),
                        facingAmount BIGINT DEFAULT 0,
                        facingSizingBp INT DEFAULT 0,
                        raiserCount SMALLINT DEFAULT 0,
                        callerCount SMALLINT DEFAULT 0,
                        playersInHand SMALLINT DEFAULT 0
                        )""",
            "createBoardsTable": """CREATE TABLE Boards (
                            id INTEGER PRIMARY KEY,
                            handId INT NOT NULL,
                            boardId INT,
                            boardcard1 INT,  /* 0=none, 1-13=2-Ah 14-26=2-Ad 27-39=2-Ac 40-52=2-As */
                            boardcard2 INT,
                            boardcard3 INT,
                            boardcard4 INT,
                            boardcard5 INT)""",
            "createBoardFeaturesTable": """CREATE TABLE BoardFeatures (
                            id INTEGER PRIMARY KEY,
                            handId INT NOT NULL,
                            boardId SMALLINT NOT NULL DEFAULT 1,
                            street SMALLINT NOT NULL,
                            streetName VARCHAR(12) NOT NULL DEFAULT '',
                            cardCount SMALLINT NOT NULL DEFAULT 0,
                            textureMask INT NOT NULL DEFAULT 0,
                            runoutMask INT NOT NULL DEFAULT 0,
                            topRank SMALLINT NOT NULL DEFAULT 0,
                            suitStructure VARCHAR(12) NOT NULL DEFAULT '',
                            pairing VARCHAR(12) NOT NULL DEFAULT '',
                            rankBucket VARCHAR(12) NOT NULL DEFAULT '',
                            connectivity VARCHAR(16) NOT NULL DEFAULT '')""",
            "createHandsCashoutTable": """CREATE TABLE HandsCashout (
                        id INTEGER PRIMARY KEY,
                        handId INT NOT NULL,
                        playerId INT NOT NULL,
                        amount decimal,
                        fee decimal
                        )""",
            "createHandsShowdownTable": """CREATE TABLE HandsShowdown (
                        id INTEGER PRIMARY KEY,
                        handId INT NOT NULL,
                        playerId INT NOT NULL,
                        combo TEXT,
                        cards TEXT
                        )""",
            "createHandsStoveTable": """CREATE TABLE HandsStove (
                        id INTEGER PRIMARY KEY,
                        handId INT NOT NULL,
                        playerId INT NOT NULL,
                        streetId INT,
                        boardId INT,
                        hiLo TEXT NOT NULL,
                        rankId INT,
                        value INT,
                        cards TEXT,
                        ev decimal
                        )""",
            "createHandsPotsTable": """CREATE TABLE HandsPots (
                        id INTEGER PRIMARY KEY,
                        handId INT NOT NULL,
                        potId INT,
                        boardId INT,
                        hiLo TEXT NOT NULL,
                        playerId INT NOT NULL,
                        pot INT,
                        collected INT,
                        rake INT
                        )""",
        }
    return {}
