"""Primary HUD cache write and lookup queries."""

from __future__ import annotations


def hud_cache_write_queries() -> dict[str, str]:
    """Return HudCache insert, update, lookup, and hero-boundary queries."""
    query: dict[str, str] = {}
    query["insert_hudcache"] = """insert into HudCache (
            gametypeId,
            playerId,
            seats,
            position,
            tourneyTypeId,
            styleKey,
            n,
            street0VPIChance,
            street0VPI,
            street0AggrChance,
            street0Aggr,
            street0CalledRaiseChance,
            street0CalledRaiseDone,
            street0FaceRaise,
            street0_2BChance,
            street0_2BDone,
            street0_3BChance,
            street0_3BDone,
            street0_4BChance,
            street0_4BDone,
            street0_C4BChance,
            street0_C4BDone,
            street0_FoldTo2BChance,
            street0_FoldTo2BDone,
            street0_FoldTo3BChance,
            street0_FoldTo3BDone,
            street0_FoldTo4BChance,
            street0_FoldTo4BDone,
            street0_SqueezeChance,
            street0_SqueezeDone,
            raiseToStealChance,
            raiseToStealDone,
            stealChance,
            stealDone,
            success_Steal,
            street1Seen,
            street2Seen,
            street3Seen,
            street4Seen,
            sawShowdown,
            street1Aggr,
            street2Aggr,
            street3Aggr,
            street4Aggr,
            otherRaisedStreet0,
            otherRaisedStreet1,
            otherRaisedStreet2,
            otherRaisedStreet3,
            otherRaisedStreet4,
            foldToOtherRaisedStreet0,
            foldToOtherRaisedStreet1,
            foldToOtherRaisedStreet2,
            foldToOtherRaisedStreet3,
            foldToOtherRaisedStreet4,
            wonWhenSeenStreet1,
            wonWhenSeenStreet2,
            wonWhenSeenStreet3,
            wonWhenSeenStreet4,
            wonAtSD,
            raiseFirstInChance,
            raisedFirstIn,
            foldBbToStealChance,
            foldedBbToSteal,
            foldSbToStealChance,
            foldedSbToSteal,
            street1CBChance,
            street1CBDone,
            street2CBChance,
            street2CBDone,
            street3CBChance,
            street3CBDone,
            street4CBChance,
            street4CBDone,
            foldToStreet1CBChance,
            foldToStreet1CBDone,
            foldToStreet2CBChance,
            foldToStreet2CBDone,
            foldToStreet3CBChance,
            foldToStreet3CBDone,
            foldToStreet4CBChance,
            foldToStreet4CBDone,
            common,
            committed,
            winnings,
            rake,
            rakeDealt,
            rakeContributed,
            rakeWeighted,
            totalProfit,
            allInEV,
            showdownWinnings,
            nonShowdownWinnings,
            street1CheckCallRaiseChance,
            street1CheckCallDone,
            street1CheckRaiseDone,
            street2CheckCallRaiseChance,
            street2CheckCallDone,
            street2CheckRaiseDone,
            street3CheckCallRaiseChance,
            street3CheckCallDone,
            street3CheckRaiseDone,
            street4CheckCallRaiseChance,
            street4CheckCallDone,
            street4CheckRaiseDone,
            street0Calls,
            street1Calls,
            street2Calls,
            street3Calls,
            street4Calls,
            street0Bets,
            street1Bets,
            street2Bets,
            street3Bets,
            street4Bets,
            street0Raises,
            street1Raises,
            street2Raises,
            street3Raises,
            street4Raises,
            street1Discards,
            street2Discards,
            street3Discards,
            street0Limp,
            street0OpenLimpChance,
            street0OpenLimp,
            street1_3BChance,
            street1_3BDone,
            street2_3BChance,
            street2_3BDone,
            street3_3BChance,
            street3_3BDone,
            street1_4BChance,
            street1_4BDone,
            street1_FoldTo4BChance,
            street1_FoldTo4BDone,
            street2_4BChance,
            street2_4BDone,
            street2_FoldTo4BChance,
            street2_FoldTo4BDone,
            street3_4BChance,
            street3_4BDone,
            street3_FoldTo4BChance,
            street3_FoldTo4BDone,
            street1OpenChance,
            street1OpenDone,
            street2OpenChance,
            street2OpenDone,
            street3OpenChance,
            street3OpenDone,
            flg_f_fold,
            flg_t_fold,
            flg_r_fold,
            street1FirstRaise,
            street2FirstRaise,
            street3FirstRaise,
            street1FaceRaise,
            street2FaceRaise,
            street3FaceRaise,
            flg_f_donk_def_opp,
            flg_t_float_opp,
            flg_t_float,
            flg_t_float_def_opp,
            flg_r_float_opp,
            flg_r_float,
            flg_r_float_def_opp,
            flg_t_donk_def_opp,
            flg_r_donk_def_opp,
            street1_FoldTo3BChance,
            street1_FoldTo3BDone,
            street2_FoldTo3BChance,
            street2_FoldTo3BDone,
            street3_FoldTo3BChance,
            street3_FoldTo3BDone,
            street0_FoldToSqueezeChance,
            street0_FoldToSqueezeDone,
            street0_FaceLimpers,
            cnt_gp_open_opp,
            cnt_gp_2x,
            cnt_gp_os,
            cnt_gp_limp,
            flg_blind_ds,
            flg_blind_db,
            flg_blind_k,
            flg_faced_allin,
            flg_fold_to_allin,
            cnt_f_bet_facing,
            val_f_bet_facing_bp,
            cnt_t_bet_facing,
            val_t_bet_facing_bp,
            cnt_r_bet_facing,
            val_r_bet_facing_bp,
            cnt_p_2bet_facing,
            val_p_2bet_facing_bp,
            cnt_p_3bet_facing,
            val_p_3bet_facing_bp,
            cnt_p_4bet_facing,
            val_p_4bet_facing_bp,
            cnt_f_bet_made,
            val_f_bet_made_bp,
            cnt_t_bet_made,
            val_t_bet_made_bp,
            cnt_r_bet_made,
            val_r_bet_made_bp,
            cnt_f_spr,
            val_f_spr,
            cnt_t_spr,
            val_t_spr,
            cnt_r_spr,
            val_r_spr,
            cnt_p_raise_made,
            val_p_raise_made_bp,
            cnt_f_raise_made,
            val_f_raise_made_bp,
            cnt_t_raise_made,
            val_t_raise_made_bp,
            cnt_r_raise_made,
            val_r_raise_made_bp,
            cnt_f_2bet_facing,
            val_f_2bet_facing_bp,
            cnt_f_3bet_facing,
            val_f_3bet_facing_bp,
            cnt_f_4bet_facing,
            val_f_4bet_facing_bp,
            cnt_t_2bet_facing,
            val_t_2bet_facing_bp,
            cnt_t_3bet_facing,
            val_t_3bet_facing_bp,
            cnt_t_4bet_facing,
            val_t_4bet_facing_bp,
            cnt_r_2bet_facing,
            val_r_2bet_facing_bp,
            cnt_r_3bet_facing,
            val_r_3bet_facing_bp,
            cnt_r_4bet_facing,
            val_r_4bet_facing_bp,
            amt_blind,
            amt_bet_p,
            amt_bet_f,
            amt_bet_t,
            amt_bet_r,
            amt_bet_ttl,
            cnt_p_raise_facing,
            val_p_raise_facing_bp,
            cnt_f_raise_facing,
            val_f_raise_facing_bp,
            cnt_t_raise_facing,
            val_t_raise_facing_bp,
            cnt_r_raise_facing,
            val_r_raise_facing_bp,
            cnt_p_raise_made_2,
            val_p_raise_made_2_bp,
            cnt_f_raise_made_2,
            val_f_raise_made_2_bp,
            cnt_t_raise_made_2,
            val_t_raise_made_2_bp,
            cnt_r_raise_made_2,
            val_r_raise_made_2_bp,
            cnt_p_5bet_facing,
            val_p_5bet_facing_bp,
            street2DelayedCBChance,
            street2DelayedCBDone,
            street2ProbeChance,
            street2ProbeDone,
            cnt_p_face_3bet,
            cnt_p_call_3bet,
            cnt_p_raise_3bet,
            cnt_p_face_4bet,
            cnt_p_call_4bet,
            cnt_p_raise_4bet,
            cnt_p_face_squeeze,
            cnt_p_call_squeeze,
            cnt_p_raise_squeeze,
            cnt_f_face_cbet,
            cnt_f_call_cbet,
            cnt_f_raise_cbet,
            cnt_f_face_donk,
            cnt_f_call_donk,
            cnt_f_raise_donk,
            cnt_f_face_3bet,
            cnt_f_call_3bet,
            cnt_f_raise_3bet,
            cnt_f_face_4bet,
            cnt_f_call_4bet,
            cnt_f_raise_4bet,
            cnt_t_face_cbet,
            cnt_t_call_cbet,
            cnt_t_raise_cbet,
            cnt_t_face_donk,
            cnt_t_call_donk,
            cnt_t_raise_donk,
            cnt_t_face_3bet,
            cnt_t_call_3bet,
            cnt_t_raise_3bet,
            cnt_t_face_4bet,
            cnt_t_call_4bet,
            cnt_t_raise_4bet,
            cnt_t_face_float,
            cnt_t_call_float,
            cnt_t_raise_float,
            cnt_r_face_cbet,
            cnt_r_call_cbet,
            cnt_r_raise_cbet,
            cnt_r_face_donk,
            cnt_r_call_donk,
            cnt_r_raise_donk,
            cnt_r_face_3bet,
            cnt_r_call_3bet,
            cnt_r_raise_3bet,
            cnt_r_face_4bet,
            cnt_r_call_4bet,
            cnt_r_raise_4bet,
            cnt_r_face_float,
            cnt_r_call_float,
            cnt_r_raise_float)
        values (%s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, %s,
                %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s,
                %s)"""

    query["update_hudcache"] = """
        UPDATE HudCache SET
        n=n+%s,
        street0VPIChance=street0VPIChance+%s,
        street0VPI=street0VPI+%s,
        street0AggrChance=street0AggrChance+%s,
        street0Aggr=street0Aggr+%s,
        street0CalledRaiseChance=street0CalledRaiseChance+%s,
        street0CalledRaiseDone=street0CalledRaiseDone+%s,
        street0FaceRaise=street0FaceRaise+%s,
        street0_2BChance=street0_2BChance+%s,
        street0_2BDone=street0_2BDone+%s,
        street0_3BChance=street0_3BChance+%s,
        street0_3BDone=street0_3BDone+%s,
        street0_4BChance=street0_4BChance+%s,
        street0_4BDone=street0_4BDone+%s,
        street0_C4BChance=street0_C4BChance+%s,
        street0_C4BDone=street0_C4BDone+%s,
        street0_FoldTo2BChance=street0_FoldTo2BChance+%s,
        street0_FoldTo2BDone=street0_FoldTo2BDone+%s,
        street0_FoldTo3BChance=street0_FoldTo3BChance+%s,
        street0_FoldTo3BDone=street0_FoldTo3BDone+%s,
        street0_FoldTo4BChance=street0_FoldTo4BChance+%s,
        street0_FoldTo4BDone=street0_FoldTo4BDone+%s,
        street0_SqueezeChance=street0_SqueezeChance+%s,
        street0_SqueezeDone=street0_SqueezeDone+%s,
        raiseToStealChance=raiseToStealChance+%s,
        raiseToStealDone=raiseToStealDone+%s,
        stealChance=stealChance+%s,
        stealDone=stealDone+%s,
        success_Steal=success_Steal+%s,
        street1Seen=street1Seen+%s,
        street2Seen=street2Seen+%s,
        street3Seen=street3Seen+%s,
        street4Seen=street4Seen+%s,
        sawShowdown=sawShowdown+%s,
        street1Aggr=street1Aggr+%s,
        street2Aggr=street2Aggr+%s,
        street3Aggr=street3Aggr+%s,
        street4Aggr=street4Aggr+%s,
        otherRaisedStreet0=otherRaisedStreet0+%s,
        otherRaisedStreet1=otherRaisedStreet1+%s,
        otherRaisedStreet2=otherRaisedStreet2+%s,
        otherRaisedStreet3=otherRaisedStreet3+%s,
        otherRaisedStreet4=otherRaisedStreet4+%s,
        foldToOtherRaisedStreet0=foldToOtherRaisedStreet0+%s,
        foldToOtherRaisedStreet1=foldToOtherRaisedStreet1+%s,
        foldToOtherRaisedStreet2=foldToOtherRaisedStreet2+%s,
        foldToOtherRaisedStreet3=foldToOtherRaisedStreet3+%s,
        foldToOtherRaisedStreet4=foldToOtherRaisedStreet4+%s,
        wonWhenSeenStreet1=wonWhenSeenStreet1+%s,
        wonWhenSeenStreet2=wonWhenSeenStreet2+%s,
        wonWhenSeenStreet3=wonWhenSeenStreet3+%s,
        wonWhenSeenStreet4=wonWhenSeenStreet4+%s,
        wonAtSD=wonAtSD+%s,
        raiseFirstInChance=raiseFirstInChance+%s,
        raisedFirstIn=raisedFirstIn+%s,
        foldBbToStealChance=foldBbToStealChance+%s,
        foldedBbToSteal=foldedBbToSteal+%s,
        foldSbToStealChance=foldSbToStealChance+%s,
        foldedSbToSteal=foldedSbToSteal+%s,
        street1CBChance=street1CBChance+%s,
        street1CBDone=street1CBDone+%s,
        street2CBChance=street2CBChance+%s,
        street2CBDone=street2CBDone+%s,
        street3CBChance=street3CBChance+%s,
        street3CBDone=street3CBDone+%s,
        street4CBChance=street4CBChance+%s,
        street4CBDone=street4CBDone+%s,
        foldToStreet1CBChance=foldToStreet1CBChance+%s,
        foldToStreet1CBDone=foldToStreet1CBDone+%s,
        foldToStreet2CBChance=foldToStreet2CBChance+%s,
        foldToStreet2CBDone=foldToStreet2CBDone+%s,
        foldToStreet3CBChance=foldToStreet3CBChance+%s,
        foldToStreet3CBDone=foldToStreet3CBDone+%s,
        foldToStreet4CBChance=foldToStreet4CBChance+%s,
        foldToStreet4CBDone=foldToStreet4CBDone+%s,
        common=common+%s,
        committed=committed+%s,
        winnings=winnings+%s,
        rake=rake+%s,
        rakeDealt=rakeDealt+%s,
        rakeContributed=rakeContributed+%s,
        rakeWeighted=rakeWeighted+%s,
        totalProfit=totalProfit+%s,
        allInEV=allInEV+%s,
        showdownWinnings=showdownWinnings+%s,
        nonShowdownWinnings=nonShowdownWinnings+%s,
        street1CheckCallRaiseChance=street1CheckCallRaiseChance+%s,
        street1CheckCallDone=street1CheckCallDone+%s,
        street1CheckRaiseDone=street1CheckRaiseDone+%s,
        street2CheckCallRaiseChance=street2CheckCallRaiseChance+%s,
        street2CheckCallDone=street2CheckCallDone+%s,
        street2CheckRaiseDone=street2CheckRaiseDone+%s,
        street3CheckCallRaiseChance=street3CheckCallRaiseChance+%s,
        street3CheckCallDone=street3CheckCallDone+%s,
        street3CheckRaiseDone=street3CheckRaiseDone+%s,
        street4CheckCallRaiseChance=street4CheckCallRaiseChance+%s,
        street4CheckCallDone=street4CheckCallDone+%s,
        street4CheckRaiseDone=street4CheckRaiseDone+%s,
        street0Calls=street0Calls+%s,
        street1Calls=street1Calls+%s,
        street2Calls=street2Calls+%s,
        street3Calls=street3Calls+%s,
        street4Calls=street4Calls+%s,
        street0Bets=street0Bets+%s,
        street1Bets=street1Bets+%s,
        street2Bets=street2Bets+%s,
        street3Bets=street3Bets+%s,
        street4Bets=street4Bets+%s,
        street0Raises=street0Raises+%s,
        street1Raises=street1Raises+%s,
        street2Raises=street2Raises+%s,
        street3Raises=street3Raises+%s,
        street4Raises=street4Raises+%s,
        street1Discards=street1Discards+%s,
        street2Discards=street2Discards+%s,
        street3Discards=street3Discards+%s,
        street0Limp=street0Limp+%s,
        street0OpenLimpChance=street0OpenLimpChance+%s,
        street0OpenLimp=street0OpenLimp+%s,
        street1_3BChance=street1_3BChance+%s,
        street1_3BDone=street1_3BDone+%s,
        street2_3BChance=street2_3BChance+%s,
        street2_3BDone=street2_3BDone+%s,
        street3_3BChance=street3_3BChance+%s,
        street3_3BDone=street3_3BDone+%s,
        street1_4BChance=street1_4BChance+%s,
        street1_4BDone=street1_4BDone+%s,
        street1_FoldTo4BChance=street1_FoldTo4BChance+%s,
        street1_FoldTo4BDone=street1_FoldTo4BDone+%s,
        street2_4BChance=street2_4BChance+%s,
        street2_4BDone=street2_4BDone+%s,
        street2_FoldTo4BChance=street2_FoldTo4BChance+%s,
        street2_FoldTo4BDone=street2_FoldTo4BDone+%s,
        street3_4BChance=street3_4BChance+%s,
        street3_4BDone=street3_4BDone+%s,
        street3_FoldTo4BChance=street3_FoldTo4BChance+%s,
        street3_FoldTo4BDone=street3_FoldTo4BDone+%s,
        street1OpenChance=street1OpenChance+%s,
        street1OpenDone=street1OpenDone+%s,
        street2OpenChance=street2OpenChance+%s,
        street2OpenDone=street2OpenDone+%s,
        street3OpenChance=street3OpenChance+%s,
        street3OpenDone=street3OpenDone+%s,
        flg_f_fold=flg_f_fold+%s,
        flg_t_fold=flg_t_fold+%s,
        flg_r_fold=flg_r_fold+%s,
        street1FirstRaise=street1FirstRaise+%s,
        street2FirstRaise=street2FirstRaise+%s,
        street3FirstRaise=street3FirstRaise+%s,
        street1FaceRaise=street1FaceRaise+%s,
        street2FaceRaise=street2FaceRaise+%s,
        street3FaceRaise=street3FaceRaise+%s,
        flg_f_donk_def_opp=flg_f_donk_def_opp+%s,
        flg_t_float_opp=flg_t_float_opp+%s,
        flg_t_float=flg_t_float+%s,
        flg_t_float_def_opp=flg_t_float_def_opp+%s,
        flg_r_float_opp=flg_r_float_opp+%s,
        flg_r_float=flg_r_float+%s,
        flg_r_float_def_opp=flg_r_float_def_opp+%s,
        flg_t_donk_def_opp=flg_t_donk_def_opp+%s,
        flg_r_donk_def_opp=flg_r_donk_def_opp+%s,
        street1_FoldTo3BChance=street1_FoldTo3BChance+%s,
        street1_FoldTo3BDone=street1_FoldTo3BDone+%s,
        street2_FoldTo3BChance=street2_FoldTo3BChance+%s,
        street2_FoldTo3BDone=street2_FoldTo3BDone+%s,
        street3_FoldTo3BChance=street3_FoldTo3BChance+%s,
        street3_FoldTo3BDone=street3_FoldTo3BDone+%s,
        street0_FoldToSqueezeChance=street0_FoldToSqueezeChance+%s,
        street0_FoldToSqueezeDone=street0_FoldToSqueezeDone+%s,
        street0_FaceLimpers=street0_FaceLimpers+%s,
        cnt_gp_open_opp=cnt_gp_open_opp+%s,
        cnt_gp_2x=cnt_gp_2x+%s,
        cnt_gp_os=cnt_gp_os+%s,
        cnt_gp_limp=cnt_gp_limp+%s,
        flg_blind_ds=flg_blind_ds+%s,
        flg_blind_db=flg_blind_db+%s,
        flg_blind_k=flg_blind_k+%s,
        flg_faced_allin=flg_faced_allin+%s,
        flg_fold_to_allin=flg_fold_to_allin+%s,
        cnt_f_bet_facing=cnt_f_bet_facing+%s,
        val_f_bet_facing_bp=val_f_bet_facing_bp+%s,
        cnt_t_bet_facing=cnt_t_bet_facing+%s,
        val_t_bet_facing_bp=val_t_bet_facing_bp+%s,
        cnt_r_bet_facing=cnt_r_bet_facing+%s,
        val_r_bet_facing_bp=val_r_bet_facing_bp+%s,
        cnt_p_2bet_facing=cnt_p_2bet_facing+%s,
        val_p_2bet_facing_bp=val_p_2bet_facing_bp+%s,
        cnt_p_3bet_facing=cnt_p_3bet_facing+%s,
        val_p_3bet_facing_bp=val_p_3bet_facing_bp+%s,
        cnt_p_4bet_facing=cnt_p_4bet_facing+%s,
        val_p_4bet_facing_bp=val_p_4bet_facing_bp+%s,
        cnt_f_bet_made=cnt_f_bet_made+%s,
        val_f_bet_made_bp=val_f_bet_made_bp+%s,
        cnt_t_bet_made=cnt_t_bet_made+%s,
        val_t_bet_made_bp=val_t_bet_made_bp+%s,
        cnt_r_bet_made=cnt_r_bet_made+%s,
        val_r_bet_made_bp=val_r_bet_made_bp+%s,
        cnt_f_spr=cnt_f_spr+%s,
        val_f_spr=val_f_spr+%s,
        cnt_t_spr=cnt_t_spr+%s,
        val_t_spr=val_t_spr+%s,
        cnt_r_spr=cnt_r_spr+%s,
        val_r_spr=val_r_spr+%s,
        cnt_p_raise_made=cnt_p_raise_made+%s,
        val_p_raise_made_bp=val_p_raise_made_bp+%s,
        cnt_f_raise_made=cnt_f_raise_made+%s,
        val_f_raise_made_bp=val_f_raise_made_bp+%s,
        cnt_t_raise_made=cnt_t_raise_made+%s,
        val_t_raise_made_bp=val_t_raise_made_bp+%s,
        cnt_r_raise_made=cnt_r_raise_made+%s,
        val_r_raise_made_bp=val_r_raise_made_bp+%s,
        cnt_f_2bet_facing=cnt_f_2bet_facing+%s,
        val_f_2bet_facing_bp=val_f_2bet_facing_bp+%s,
        cnt_f_3bet_facing=cnt_f_3bet_facing+%s,
        val_f_3bet_facing_bp=val_f_3bet_facing_bp+%s,
        cnt_f_4bet_facing=cnt_f_4bet_facing+%s,
        val_f_4bet_facing_bp=val_f_4bet_facing_bp+%s,
        cnt_t_2bet_facing=cnt_t_2bet_facing+%s,
        val_t_2bet_facing_bp=val_t_2bet_facing_bp+%s,
        cnt_t_3bet_facing=cnt_t_3bet_facing+%s,
        val_t_3bet_facing_bp=val_t_3bet_facing_bp+%s,
        cnt_t_4bet_facing=cnt_t_4bet_facing+%s,
        val_t_4bet_facing_bp=val_t_4bet_facing_bp+%s,
        cnt_r_2bet_facing=cnt_r_2bet_facing+%s,
        val_r_2bet_facing_bp=val_r_2bet_facing_bp+%s,
        cnt_r_3bet_facing=cnt_r_3bet_facing+%s,
        val_r_3bet_facing_bp=val_r_3bet_facing_bp+%s,
        cnt_r_4bet_facing=cnt_r_4bet_facing+%s,
        val_r_4bet_facing_bp=val_r_4bet_facing_bp+%s,
        amt_blind=amt_blind+%s,
        amt_bet_p=amt_bet_p+%s,
        amt_bet_f=amt_bet_f+%s,
        amt_bet_t=amt_bet_t+%s,
        amt_bet_r=amt_bet_r+%s,
        amt_bet_ttl=amt_bet_ttl+%s,
        cnt_p_raise_facing=cnt_p_raise_facing+%s,
        val_p_raise_facing_bp=val_p_raise_facing_bp+%s,
        cnt_f_raise_facing=cnt_f_raise_facing+%s,
        val_f_raise_facing_bp=val_f_raise_facing_bp+%s,
        cnt_t_raise_facing=cnt_t_raise_facing+%s,
        val_t_raise_facing_bp=val_t_raise_facing_bp+%s,
        cnt_r_raise_facing=cnt_r_raise_facing+%s,
        val_r_raise_facing_bp=val_r_raise_facing_bp+%s,
        cnt_p_raise_made_2=cnt_p_raise_made_2+%s,
        val_p_raise_made_2_bp=val_p_raise_made_2_bp+%s,
        cnt_f_raise_made_2=cnt_f_raise_made_2+%s,
        val_f_raise_made_2_bp=val_f_raise_made_2_bp+%s,
        cnt_t_raise_made_2=cnt_t_raise_made_2+%s,
        val_t_raise_made_2_bp=val_t_raise_made_2_bp+%s,
        cnt_r_raise_made_2=cnt_r_raise_made_2+%s,
        val_r_raise_made_2_bp=val_r_raise_made_2_bp+%s,
        cnt_p_5bet_facing=cnt_p_5bet_facing+%s,
        val_p_5bet_facing_bp=val_p_5bet_facing_bp+%s,
        street2DelayedCBChance=street2DelayedCBChance+%s,
        street2DelayedCBDone=street2DelayedCBDone+%s,
        street2ProbeChance=street2ProbeChance+%s,
        street2ProbeDone=street2ProbeDone+%s,
        cnt_p_face_3bet=cnt_p_face_3bet+%s,
        cnt_p_call_3bet=cnt_p_call_3bet+%s,
        cnt_p_raise_3bet=cnt_p_raise_3bet+%s,
        cnt_p_face_4bet=cnt_p_face_4bet+%s,
        cnt_p_call_4bet=cnt_p_call_4bet+%s,
        cnt_p_raise_4bet=cnt_p_raise_4bet+%s,
        cnt_p_face_squeeze=cnt_p_face_squeeze+%s,
        cnt_p_call_squeeze=cnt_p_call_squeeze+%s,
        cnt_p_raise_squeeze=cnt_p_raise_squeeze+%s,
        cnt_f_face_cbet=cnt_f_face_cbet+%s,
        cnt_f_call_cbet=cnt_f_call_cbet+%s,
        cnt_f_raise_cbet=cnt_f_raise_cbet+%s,
        cnt_f_face_donk=cnt_f_face_donk+%s,
        cnt_f_call_donk=cnt_f_call_donk+%s,
        cnt_f_raise_donk=cnt_f_raise_donk+%s,
        cnt_f_face_3bet=cnt_f_face_3bet+%s,
        cnt_f_call_3bet=cnt_f_call_3bet+%s,
        cnt_f_raise_3bet=cnt_f_raise_3bet+%s,
        cnt_f_face_4bet=cnt_f_face_4bet+%s,
        cnt_f_call_4bet=cnt_f_call_4bet+%s,
        cnt_f_raise_4bet=cnt_f_raise_4bet+%s,
        cnt_t_face_cbet=cnt_t_face_cbet+%s,
        cnt_t_call_cbet=cnt_t_call_cbet+%s,
        cnt_t_raise_cbet=cnt_t_raise_cbet+%s,
        cnt_t_face_donk=cnt_t_face_donk+%s,
        cnt_t_call_donk=cnt_t_call_donk+%s,
        cnt_t_raise_donk=cnt_t_raise_donk+%s,
        cnt_t_face_3bet=cnt_t_face_3bet+%s,
        cnt_t_call_3bet=cnt_t_call_3bet+%s,
        cnt_t_raise_3bet=cnt_t_raise_3bet+%s,
        cnt_t_face_4bet=cnt_t_face_4bet+%s,
        cnt_t_call_4bet=cnt_t_call_4bet+%s,
        cnt_t_raise_4bet=cnt_t_raise_4bet+%s,
        cnt_t_face_float=cnt_t_face_float+%s,
        cnt_t_call_float=cnt_t_call_float+%s,
        cnt_t_raise_float=cnt_t_raise_float+%s,
        cnt_r_face_cbet=cnt_r_face_cbet+%s,
        cnt_r_call_cbet=cnt_r_call_cbet+%s,
        cnt_r_raise_cbet=cnt_r_raise_cbet+%s,
        cnt_r_face_donk=cnt_r_face_donk+%s,
        cnt_r_call_donk=cnt_r_call_donk+%s,
        cnt_r_raise_donk=cnt_r_raise_donk+%s,
        cnt_r_face_3bet=cnt_r_face_3bet+%s,
        cnt_r_call_3bet=cnt_r_call_3bet+%s,
        cnt_r_raise_3bet=cnt_r_raise_3bet+%s,
        cnt_r_face_4bet=cnt_r_face_4bet+%s,
        cnt_r_call_4bet=cnt_r_call_4bet+%s,
        cnt_r_raise_4bet=cnt_r_raise_4bet+%s,
        cnt_r_face_float=cnt_r_face_float+%s,
        cnt_r_call_float=cnt_r_call_float+%s,
        cnt_r_raise_float=cnt_r_raise_float+%s
    WHERE id=%s"""

    query["select_hudcache_ring"] = """
                SELECT id
                FROM HudCache
                WHERE gametypeId=%s
                AND   playerId=%s
                AND   seats=%s
                AND   position=%s
                AND   tourneyTypeId is NULL
                AND   styleKey = %s"""

    query["select_hudcache_tour"] = """
                SELECT id
                FROM HudCache
                WHERE gametypeId=%s
                AND   playerId=%s
                AND   seats=%s
                AND   position=%s
                AND   tourneyTypeId=%s
                AND   styleKey = %s"""

    query["get_hero_hudcache_start"] = """select min(hc.styleKey)
                                               from HudCache hc
                                               where hc.playerId in <playerid_list>
                                               and   hc.styleKey like 'd%'"""

    ####################################
    # Queries to insert/update cardscache
    ####################################

    return query

