[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[metadata]
name = "fpdb"
version = "3"
description = "Free Poker Database"
author = "FPDB team"
author_email = "fpdb-main@lists.sourceforge.net"

[options]
packages = ["fpdb"]
package_dir = { "fpdb": "pyfpdb" }
data_files = [
    ["usr/share/pixmaps", [
        "gfx/fpdb-icon.png",
        "gfx/fpdb-icon2.png",
        "gfx/fpdb-cards.png"
    ]],
    ["usr/share/applications", ["files/fpdb.desktop"]],
    ["usr/share/python-fpdb", [
        "pyfpdb/logging.conf",
        "pyfpdb/HUD_config.xml.example"
    ]],
    ["usr/share/python-fpdb/cards/backs", ["gfx/cards/backs/*"]],
    ["usr/share/python-fpdb/cards/bordered", ["gfx/cards/bordered/*"]],
    ["usr/share/python-fpdb/cards/colour", ["gfx/cards/colour/*"]],
    ["usr/share/python-fpdb/cards/simple", ["gfx/cards/simple/*"]],
    ["usr/share/python-fpdb/cards/white", ["gfx/cards/white/*"]],
]

[options.command]
install_translations = "fpdb:InstallTranslations"