@startuml classes
set namespaceSeparator none
class "Aux_Seats" as Aux_Base.Aux_Seats {
  adj : list
  aw_class_window
  displayed : bool
  m_windows : dict
  positions : dict
  timer_on : bool
  uses_timer : bool
  adj_seats()
  configure_event_cb(widget, i)
  create()
  create_common(x, y)
  create_contents()
  create_scale_position(x, y)
  destroy()
  hide()
  move_windows()
  resize_windows()
  save_layout()
  update_contents()
  update_gui(new_hand_id)
}
class "Aux_Window" as Aux_Base.Aux_Window {
  config
  hud
  params
  count_seats_with_cards(cards)
  create()
  destroy()
  get_id_from_seat(seat)
  move_windows()
  save_layout()
  update_data()
  update_gui()
}
class "Seat_Window" as Aux_Base.Seat_Window {
  aw : NoneType
  lastPos : NoneType
  seat : NoneType
  button_press_left(event)
  button_press_middle(event)
  button_press_right(event)
  button_release_left(event)
  button_release_middle(event)
  button_release_right(event)
  create_contents()
  mouseMoveEvent(event)
  mousePressEvent(event)
  mouseReleaseEvent(event)
  update_contents()
}
Aux_Base.Aux_Seats --|> Aux_Base.Aux_Window
Aux_Base.Seat_Window --* Aux_Base.Aux_Seats : aw_class_window
@enduml
