@startuml classes
set namespaceSeparator none
class "Entraction" as EntractionToFpdb.Entraction {
  Lim_Blinds : dict
  codepage : tuple
  filetype : str
  games : dict
  limits : dict
  re_Action
  re_Antes
  re_Board
  re_BringIn
  re_Button
  re_CollectPot
  re_DateTime
  re_GameEnds
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_Max
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_PostSecondSB
  re_ShowdownAction
  re_ShownCards
  re_SplitHands
  siteId : int
  sitename : str
  substitutions : dict
  sym : dict
  compilePlayerRegexs(hand)
  determineGameType(handText)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
