@startuml classes
set namespaceSeparator none
class "AppURLopener" as SummaryEverleaf.AppURLopener {
  version : str
}
class "EverleafSummary" as SummaryEverleaf.EverleafSummary {
  parser
  main(id)
}
class "SummaryParser" as SummaryEverleaf.SummaryParser {
  Results : dict
  SiteName : NoneType
  TempResultPos : int
  TempResultStore : list
  TourneyBuyIn : NoneType
  TourneyEndTime : NoneType
  TourneyGameType : NoneType
  TourneyId : NoneType
  TourneyName : NoneType
  TourneyPool : NoneType
  TourneyRebuys : NoneType
  TourneyStartTime : NoneType
  TourneyStructure : NoneType
  TourneysPlayers : NoneType
  nextAllowRebuys : bool
  nextBuyIn : bool
  nextEndTime : bool
  nextGameType : bool
  nextPlayers : bool
  nextPool : bool
  nextStartTime : bool
  nextStructure : bool
  nofill : bool
  parseResultsA : bool
  parseResultsB : bool
  end_div()
  end_h1()
  end_td()
  get_attr(attrs, key)
  start_div(attrs)
  start_h1(attrs)
  start_input(attrs)
  start_meta(attrs)
  start_td(attrs)
}
SummaryEverleaf.SummaryParser --* SummaryEverleaf.EverleafSummary : parser
@enduml
