@startuml classes
set namespaceSeparator none
class "<color:red>FpdbDatabaseError</color>" as Exceptions.FpdbDatabaseError {
}
class "<color:red>FpdbEndOfFile</color>" as Exceptions.FpdbEndOfFile {
}
class "<color:red>FpdbError</color>" as Exceptions.FpdbError {
  value
}
class "<color:red>FpdbHandDuplicate</color>" as Exceptions.FpdbHandDuplicate {
}
class "<color:red>FpdbHandError</color>" as Exceptions.FpdbHandError {
}
class "<color:red>FpdbHandPartial</color>" as Exceptions.FpdbHandPartial {
}
class "<color:red>FpdbHandSkipped</color>" as Exceptions.FpdbHandSkipped {
}
class "<color:red>FpdbMySQLAccessDenied</color>" as Exceptions.FpdbMySQLAccessDenied {
  errmsg : str
  value : str
}
class "<color:red>FpdbMySQLError</color>" as Exceptions.FpdbMySQLError {
}
class "<color:red>FpdbMySQLNoDatabase</color>" as Exceptions.FpdbMySQLNoDatabase {
  errmsg : str
  value : str
}
class "<color:red>FpdbParseError</color>" as Exceptions.FpdbParseError {
  hid : str
  value : str
}
class "<color:red>FpdbPostgresqlAccessDenied</color>" as Exceptions.FpdbPostgresqlAccessDenied {
  errmsg : str
  value : str
}
class "<color:red>FpdbPostgresqlNoDatabase</color>" as Exceptions.FpdbPostgresqlNoDatabase {
  errmsg : str
  value : str
}
Exceptions.FpdbDatabaseError --|> Exceptions.FpdbError
Exceptions.FpdbEndOfFile --|> Exceptions.FpdbHandError
Exceptions.FpdbHandDuplicate --|> Exceptions.FpdbHandError
Exceptions.FpdbHandError --|> Exceptions.FpdbError
Exceptions.FpdbHandPartial --|> Exceptions.FpdbParseError
Exceptions.FpdbHandSkipped --|> Exceptions.FpdbParseError
Exceptions.FpdbMySQLAccessDenied --|> Exceptions.FpdbDatabaseError
Exceptions.FpdbMySQLError --|> Exceptions.FpdbDatabaseError
Exceptions.FpdbMySQLNoDatabase --|> Exceptions.FpdbDatabaseError
Exceptions.FpdbParseError --|> Exceptions.FpdbError
Exceptions.FpdbPostgresqlAccessDenied --|> Exceptions.FpdbDatabaseError
Exceptions.FpdbPostgresqlNoDatabase --|> Exceptions.FpdbDatabaseError
@enduml
