@startuml classes
set namespaceSeparator none
class "Filters" as Filters.Filters {
  Button1
  Button2
  callback : dict
  cards : dict
  cbCurrencies : dict
  cbGames : dict
  cbGraphops : dict
  cbGroups : dict
  cbLimits : dict
  cbPositions : dict
  cbSites : dict
  cbTourney : dict
  conf
  currencyName : dict
  cursor
  day_start : int, float
  db
  display : dict
  end_date
  filterText : dict
  gameList
  gameName : dict
  heroList
  leHeroes : dict
  phands : NoneType
  rb : dict
  sbSeats : dict
  siteid : dict
  sql
  start_date
  type : str, NoneType
  createCardsControls(hbox)
  createCardsWidget(grid)
  createTourneyTypeLine(hbox, tourneyType)
  fillCurrenciesFrame(frame)
  fillDateFrame(frame)
  fillGamesFrame(frame)
  fillGraphOpsFrame(frame)
  fillGroupsFrame(frame, display)
  fillHoleCardsFrame(frame)
  fillLimitsFrame(frame, display)
  fillPlayerFrame(frame, display)
  fillPositionsFrame(frame, display)
  fillSeatsFrame(frame)
  fillSitesFrame(frame)
  fillTourneyFrame(frame)
  fillTourneyTypesFrame(vbox)
  getCards()
  getCurrencies()
  getDates()
  getGames()
  getGraphOps()
  getGroups()
  getHeroes()
  getLimits()
  getNumHands()
  getNumTourneys()
  getPositions()
  getSeats()
  getSiteIds()
  getSites()
  getTourneyTypes()
  getType()
  get_limits_where_clause(limits)
  make_filter()
  registerButton1Callback(callback)
  registerButton1Name(title)
  registerButton2Callback(callback)
  registerButton2Name(title)
  registerCardsCallback(callback)
  replace_placeholders_with_filter_values(query)
}
@enduml
