@startuml classes
set namespaceSeparator none
class "fpdb" as fpdb.fpdb {
  closeq : Queue
  config : Config
  db : NoneType
  dia_confirm
  display_config_created_dialogue : bool
  display_site_preferences : bool
  h_start_date
  hud_preferences_columns : int
  hud_preferences_game
  hud_preferences_rows : int
  lock
  lockTakenBy : NoneType
  nb
  nb_tab_names : list
  pages : list
  quitting : bool
  settings : dict
  sql
  start_date
  status_bar : NoneType
  tab_names : list
  tabs : list
  threads : list
  visible : bool
  add_and_display_tab(new_page, new_tab_name)
  autoenableSite(text, checkbox)
  browseClicked(widget, parent, path)
  createMenuBar()
  detect_clicked(widget, data)
  dia_about(widget, data)
  dia_advanced_preferences(widget, data)
  dia_database_stats(widget, data)
  dia_dump_db(widget, data)
  dia_import_filters(checkState)
  dia_logs(widget, data)
  dia_rebuild_indexes(widget, data)
  dia_recreate_hudcache(widget, data)
  dia_recreate_tables(widget, data)
  dia_site_preferences(widget, data)
  display_tab(new_tab_name)
  hud_preferences_combo_selection(widget)
  info_box(str1, str2)
  launch_ppt()
  load_profile(create_db)
  obtain_global_lock(source)
  process_close_messages()
  quit(widget, data)
  release_global_lock()
  reload_config()
  tabGraphViewer(widget, data)
  tabStove(widget, data)
  tabTourneyGraphViewer(widget, data)
  tab_auto_import(widget, data)
  tab_bulk_import(widget, data)
  tab_hand_viewer(widget, data)
  tab_imap_import(widget, data)
  tab_main_help(widget, data)
  tab_odds_calc(widget, data)
  tab_positional_stats(widget, data)
  tab_ring_player_stats(widget, data)
  tab_session_stats(widget, data)
  tab_tourney_import(widget, data)
  tab_tourney_player_stats(widget, data)
  tab_tourney_viewer_stats(widget, data)
  validate_config()
  warning_box(string, diatitle)
}
@enduml
