@startuml classes
set namespaceSeparator none
class "FullTiltPokerSummary" as FullTiltPokerSummary.FullTiltPokerSummary {
  addOnCost : int
  buyin : int
  buyinCurrency : str, NoneType
  chanceCount : int
  codepage : list
  currency : str, NoneType
  endTime : datetime
  entries : int
  fee : int
  games : dict
  guaranteeAmt : int
  isAddOn : bool
  isCashOut : bool
  isChance : bool
  isFast : bool
  isGuarantee : bool
  isKO : bool
  isMatrix : bool
  isMultiEntry : bool
  isNewToGame : bool
  isOnDemand : bool
  isReEntry : bool
  isRebuy : bool
  isSatellite : bool
  isShootout : bool
  isSng : bool
  isStep : bool
  koBounty : int
  limits : dict
  maxseats : int
  months : dict
  prizepool : int
  re_BuyInXLS
  re_Chance
  re_Currency
  re_DateTimeXLS
  re_Finished
  re_GameXLS
  re_HeroXLS
  re_Identify
  re_Max
  re_Multi
  re_NewToGame
  re_Player
  re_Speed
  re_Stack
  re_TourNo
  re_TourneyExtraInfo
  re_TourneyInfo
  re_WinningsXLS
  rebuyCost : int
  speed : str
  stack
  startTime : datetime
  stepNo : int
  substitutions : dict
  tourNo : int
  tourneyName
  getSplitRe(head)
  parseSummary()
  parseSummaryFile()
  parseSummaryXLS()
  readTourneyName(tourneyName, matchNo)
  setCurrency(m, currency)
}
@enduml
