@startuml classes
set namespaceSeparator none
class "GuiAutoImport" as GuiAutoImport.GuiAutoImport {
  config
  database
  doAutoImportBool : bool
  importer
  importtimer : NoneType
  input_settings : dict
  intervalEntry
  intervalLabel
  parent : NoneType
  password
  pipe_to_hud : Popen, NoneType
  server
  settings
  sql : NoneType
  startButton
  textview
  user
  addSites(vbox1, vbox2)
  addText(text)
  browseClicked()
  createSiteLine(hbox1, hbox2, site, iconpath, type, path, filter_name, active)
  detect_hh_dirs(widget, data)
  do_import()
  get_vbox()
  posix_detect_hh_dirs(site)
  reset_startbutton()
  setupGui()
  startClicked()
}
@enduml
