@startuml classes
set namespaceSeparator none
class "GuiGraphViewer" as GuiGraphViewer.GuiGraphViewer {
  ax
  canvas : NoneType
  conf
  db
  debug : bool
  exportFile : NoneType
  fig : NoneType, Figure
  filters
  graphBox
  parent
  sql
  clearGraphData()
  exportGraph()
  generateGraph(widget)
  getRingProfitGraph(names, sites, limits, games, currencies, units)
}
@enduml
