@startuml classes
set namespaceSeparator none
class "GuiImapFetcher" as GuiImapFetcher.GuiImapFetcher {
  buttonsHBox
  config
  db
  importAllButton
  mainVBox
  passwords : dict
  rowVBox
  saveButton
  statusLabel
  displayConfig()
  get_vbox()
  importAllClicked(widget, data)
  saveClicked(widget, data)
}
@enduml
