@startuml classes
set namespaceSeparator none
class "GuiTourneyGraphViewer" as GuiTourneyGraphViewer.GuiTourneyGraphViewer {
  ax
  canvas : NoneType
  conf
  db
  debug : bool
  fig : Figure, NoneType
  filters
  graphBox
  parent
  sql
  clearGraphData()
  exportGraph(widget, data)
  generateGraph(widget)
  getData(names, sites, games)
}
@enduml
