@startuml classes
set namespaceSeparator none
class "GuiTourneyViewer" as GuiTourneyViewer.GuiTourneyViewer {
  db
  displayButton
  entryPlayer
  entryTourney
  errorLabel
  interfaceHBox
  label_Player
  label_tour
  mainwin
  playerName
  siteBox
  siteName
  table
  tourneyNo : int
  displayClicked(widget, data)
  get_vbox()
  prepare(columns, rows)
  warning_box(string, diatitle)
}
@enduml
