@startuml classes
set namespaceSeparator none
class "Hud" as Hud.Hud {
  aux_windows : list
  config
  creation_attrs : NoneType
  db_hud_connection
  game_type
  hand_instance
  hud_params
  layout
  layout_set
  max
  parent
  poker_game
  site
  site_parameters
  stat_dict
  supported_games_parameters
  table
  create(hand, config, stat_dict)
  kill()
  move_table_position()
  reposition_windows()
  resize_windows()
  save_layout()
  update(hand, config)
}
@enduml
