@startuml classes
set namespaceSeparator none
class "ImportProgressDialog" as Importer.ImportProgressDialog {
  fraction : int
  handcount
  pbar
  progresstext
  total : int
  progress_update(filename, handcount)
}
class "Importer" as Importer.Importer {
  cacheSessions
  callHud
  caller
  config
  database : Database
  dirlist : dict
  faobs : NoneType
  filelist : dict
  handhistoryconverter
  idsite
  lines : NoneType
  mode : NoneType
  monitor : bool
  parent : NoneType
  pos_in_file : dict
  removeFromFileList : dict
  settings
  siteIds : dict
  sql : NoneType
  updatedsize : dict
  updatedtime : dict
  updatetime : dict
  writeq : NoneType
  writerdbs : list
  addBulkImportImportFileOrDir(inputPath, site)
  addFileToList(fpdbfile)
  addImportDirectory(dir, monitor, site, filter)
  addImportFile(filename, site)
  autoSummaryGrab(force)
  calculate_auto2(db, scale, increment)
  clearFileList()
  getCachedHHC()
  importFiles(q)
  logImport(type, file, stored, dups, partial, skipped, errs, ttime, id)
  progressNotify()
  readFile(obj, filename, site)
  runImport()
  runPostImport()
  runUpdated()
  setCacheSessions(value)
  setCallHud(value)
  setDropHudCache(value)
  setDropIndexes(value)
  setFTPArchive(value)
  setFakeCacheHHC(value)
  setHandCount(value)
  setHandsInDB(value)
  setMode(value)
  setPrintTestData(value)
  setQuiet(value)
  setStarsArchive(value)
  setThreads(value)
}
@enduml
