@startuml classes
set namespaceSeparator none
class "InterProcessLockBase" as interlocks.InterProcessLockBase {
  heldBy : NoneType, str
  name : NoneType
  acquire(source, wait, retry_time)
  acquire_impl(wait)
  getHashedName()
  locked()
  release()
}
class "InterProcessLockFcntl" as interlocks.InterProcessLockFcntl {
  lock_file_name
  lockfd : int
  acquire_impl(wait)
  getHashedName()
  release_impl()
}
class "InterProcessLockSocket" as interlocks.InterProcessLockSocket {
  portno
  socket : NoneType, socket
  acquire_impl(wait)
  release_impl()
}
class "InterProcessLockWin32" as interlocks.InterProcessLockWin32 {
  mutex : NoneType
  acquire_impl(wait)
  release_impl()
}
class "<color:red>SingleInstanceError</color>" as interlocks.SingleInstanceError {
}
interlocks.InterProcessLockFcntl --|> interlocks.InterProcessLockBase
interlocks.InterProcessLockSocket --|> interlocks.InterProcessLockBase
interlocks.InterProcessLockWin32 --|> interlocks.InterProcessLockBase
@enduml
