@startuml classes
set namespaceSeparator none
class "iPoker" as iPokerToFpdb.iPoker {
  Lim_Blinds : dict
  codepage : tuple
  copyGameHeader : bool
  currencies : dict
  filetype : str
  games : dict
  hero
  info : dict
  limits : dict
  maxseats
  months : dict
  playerWinnings : dict
  re_Action
  re_Board
  re_Buyin
  re_ClientVersion
  re_DateTime1
  re_DateTime2
  re_DateTime3
  re_EndOfHand
  re_FPP
  re_GameInfo
  re_GameInfoTrny
  re_HandInfo
  re_Hero
  re_HeroCards
  re_Identify
  re_MaxSeats
  re_Partial
  re_PlayerInfo
  re_SitsOut
  re_SplitHands
  re_TailSplitHands
  re_TotalBuyin
  re_TourNo
  re_UncalledBets
  re_non_decimal
  siteId : int
  sitename : str
  substitutions : dict
  summaryInFile : bool
  tablename : str
  tinfo : dict
  uncalledbets : bool
  compilePlayerRegexs(hand)
  determineGameType(handText)
  fixTourBlinds(hand)
  getTableTitleRe(type, table_name, tournament, table_number)
  markStreets(hand)
  parseHeader(handText, whole_file)
  playerNameFromSeatNo(seatNo, hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
