@startuml classes
set namespaceSeparator none
class "MergeSummary" as MergeSummary.MergeSummary {
  addOnChips : NoneType
  addOnCost : int
  addOnCounts : dict
  added : NoneType
  addedCurrency : NoneType
  buyInChips : int
  buyin : int
  buyinCurrency : str, NoneType
  codepage : list
  comment : NoneType
  commentTs : NoneType
  currency : NoneType, str
  endTime : NoneType
  entries : int
  fee : int
  games : dict
  games_html : dict
  gametype : dict
  guarantee : NoneType
  hero : NoneType
  isAddOn : bool
  isDoubleOrNothing : bool
  isKO : bool
  isMatrix : bool
  isRebuy : bool
  isSatellite : bool
  isShootout : bool
  isSng : bool
  isZoom : bool
  koBounty : int
  koCounts : dict
  limits : dict
  matrixIdProcessed : NoneType
  matrixMatchId : NoneType
  maxseats : int
  mixed : NoneType
  mixes : dict
  months : dict
  playerIds : dict
  players : dict
  prizepool : int
  ranks : dict
  re_DateTimeHH
  re_GameTypeHH
  re_HTMLAddons
  re_HTMLBounty
  re_HTMLBuyIn
  re_HTMLDateTime
  re_HTMLFee
  re_HTMLGameType
  re_HTMLName
  re_HTMLPlayer
  re_HTMLPrizepool
  re_HTMLRebuy
  re_HTMLStartTime
  re_HTMLTourNo
  re_HandInfoHH
  re_Identify
  re_NotFound
  re_Ticket
  re_turboHH
  rebuyChips : NoneType
  rebuyCost : int
  rebuyCounts : dict
  speed : str
  startTime : datetime, NoneType
  subTourneyBuyin : NoneType
  subTourneyFee : NoneType
  substitutions : dict
  sym : NoneType
  totalAddOnCount : NoneType
  totalRebuyCount : NoneType
  tourNo : NoneType
  tourneyComment : NoneType
  tourneyId : NoneType
  tourneyName : NoneType
  tourneyTypeId : NoneType
  tourneysPlayersIds : dict
  winnings : dict
  winningsCurrency : dict
  convert_to_decimal(string)
  getSplitRe(head)
  parseSummary()
  parseSummaryFile()
  parseSummaryFromHH(mg)
  resetInfo()
}
@enduml
