@startuml classes
set namespaceSeparator none
class "PacificPokerSummary" as PacificPokerSummary.PacificPokerSummary {
  addOnCost : int
  buyin : int
  buyinCurrency : str
  codepage : tuple
  currency : str, NoneType
  entries
  fee : int
  games : dict
  isAddOn : bool
  isRebuy : bool
  limits : dict
  prizepool
  re_Category
  re_Identify
  re_TourneyInfo
  rebuyCost : int
  substitutions : dict
  tourNo
  convert_to_decimal(string)
  getSplitRe(head)
  parseSummary()
}
@enduml
