@startuml classes
set namespaceSeparator none
class "PartyPoker" as PartyPokerToFpdb.PartyPoker {
  Lim_Blinds : dict
  NLim_Blinds_20bb : dict
  codepage : tuple
  compiledPlayers : set
  currencies : dict
  filetype : str
  games : dict
  isSNG : bool
  limits : dict
  lineSplitter : str
  months : dict
  playerMap : dict
  re_20BBmin
  re_Action
  re_Antes
  re_Blinds
  re_Board
  re_Button
  re_Cancelled
  re_CollectPot
  re_CountedSeats
  re_Disconnected
  re_GameInfo
  re_GameInfoTrny1
  re_GameInfoTrny2
  re_GameInfoTrny3
  re_GameStartLine
  re_HandInfo
  re_HeroCards
  re_Identify
  re_NewLevel
  re_NoSmallBlind
  re_PlayerInfo
  re_PostBB
  re_PostBUB
  re_PostDead
  re_PostSB
  re_ShownCards
  re_SplitHands
  re_TailSplitHands
  re_TourNoLevel
  re_emailedHand
  siteId
  siteId : int
  sitename
  sitename : str
  sites : dict
  substitutions : dict
  sym : dict
  allHandsAsList()
  compilePlayerRegexs(hand)
  determineGameType(handText)
  getTableTitleRe(type, table_name, tournament, table_number)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
