@startuml classes
set namespaceSeparator none
class "Pkr" as PkrToFpdb.Pkr {
  codepage : tuple
  compiledPlayers : set
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  mixes : dict
  months : dict
  re_Action
  re_Antes
  re_Board
  re_BringIn
  re_Button
  re_Cards
  re_CollectPot
  re_DateTime
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_Partial
  re_PlayerInfo
  re_Post
  re_PostBB
  re_PostSB
  re_ShowdownAction
  re_ShownCards
  re_SplitHands
  re_TailSplitHands
  re_sitsOut
  siteId : int
  sitename : str
  substitutions : dict
  sym : dict
  compilePlayerRegexs(hand)
  determineGameType(handText)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
