@startuml classes
set namespaceSeparator none
class "PokerTrackerSummary" as PokerTrackerSummary.PokerTrackerSummary {
  addOnCost : int
  buyin : int
  buyinCurrency : str
  codepage : list
  currency : str, NoneType
  entries
  fee : int
  games : dict
  hhtype : str
  isAddOn : bool
  isKO : bool
  isRebuy : bool
  isSatellite : bool
  isSng : bool
  koBounty : int
  limits : dict
  maxseats : int
  prizepool : int
  re_DateTime
  re_Identify
  re_Max
  re_Player
  re_Sng
  re_Speed
  re_TourneyInfo
  rebuyCost : int
  siteId
  siteName
  siteNameMap : dict
  speed : str
  stack : str
  startTime : datetime
  substitutions : dict
  tourNo
  tourneyName
  getSplitRe(head)
  parseSummary()
}
@enduml
