@startuml classes
set namespaceSeparator none
class "PokerTracker" as PokerTrackerToFpdb.PokerTracker {
  Lim_Blinds : dict
  Structures
  Structures : NoneType
  codepage : tuple
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  re_Action1
  re_Action2
  re_Antes
  re_Board1
  re_Board2
  re_Button
  re_Cancelled
  re_CollectPot1
  re_CollectPot2
  re_Currency
  re_DateTime1
  re_DateTime2
  re_DateTime3
  re_FastFold
  re_GameInfo1
  re_GameInfo2
  re_GameInfo3
  re_HandInfo_Cash
  re_HandInfo_Tour
  re_HeroCards1
  re_HeroCards2
  re_Hole
  re_Identify
  re_Max
  re_PlayerInfo1
  re_PlayerInfo2
  re_PostBB
  re_PostBoth1
  re_PostBoth2
  re_PostSB
  re_ShownCards1
  re_ShownCards2
  re_Site
  re_SplitHands
  re_TailSplitHands
  re_Tournament
  siteId
  sitename
  sites : dict
  substitutions : dict
  sym : dict
  adjustMergeTourneyStack(hand, player, amount)
  allInBlind(hand, street, action, actiontype)
  compilePlayerRegexs(hand)
  determineGameType(handText)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
