@startuml classes
set namespaceSeparator none
class "PokerStarsSummary" as PokerStarsSummary.PokerStarsSummary {
  addOnCost
  buyin : int
  buyinCurrency : str, NoneType
  codepage : list
  comment
  currency : str
  endTime : datetime
  entries : int
  fee : int
  games : dict
  hhtype : str
  isAddOn : bool
  isDoubleOrNothing : bool
  isFast : bool
  isKO : bool
  isReEntry : bool
  isRebuy : bool
  isSatellite : bool
  isSng : bool
  isSplit : bool
  koBounty : int
  limits : dict
  maxseats : int
  prizepool : int
  re_DateTime
  re_HTMLDateTime
  re_HTMLPlayer1
  re_HTMLPlayer2
  re_HTMLTourneyExtraInfo
  re_HTMLTourneyInfo
  re_Header
  re_Identify
  re_KOBounties
  re_PlayerRIO
  re_PlayerStars
  re_Rank
  re_TourNo
  re_TourneyInfo
  re_XLSDateTime
  re_XLSPlayer
  re_XLSTourneyInfo : dict
  re_emailHeader
  re_rebuyAddOn
  rebuyCost
  siteId : int
  siteName : str
  speed : str
  startTime : datetime
  substitutions : dict
  tourNo
  tourneyName
  getSplitRe(head)
  lookupStructures(date)
  parseSummary()
  parseSummaryArchive(info)
  parseSummaryFile()
  parseSummaryFromHH()
  parseSummaryHtml()
  parseSummaryXLS()
}
@enduml
