@startuml classes
set namespaceSeparator none
class "SealsWithClubs" as SealsWithClubsToFpdb.SealsWithClubs {
  codepage : tuple
  filetype : str
  games : dict
  limits : dict
  re_Action
  re_Antes
  re_Board
  re_ButtonName
  re_Cancelled
  re_CollectPot
  re_DateTime
  re_Flop
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_River
  re_ShowdownAction
  re_SplitHands
  re_Turn
  siteId : int
  sitename : str
  substitutions : dict
  compilePlayerRegexs(hand)
  determineGameType(handText)
  getTableTitleRe(type, table_name, tournament, table_number)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
