@startuml classes
set namespaceSeparator none
class "SplitHandHistory" as SplitHandHistory.SplitHandHistory {
  archive : bool
  config
  filedone : bool
  hands : int
  in_path : str
  line_addendum : str, NoneType
  line_delimiter : str, NoneType
  out_path : NoneType
  re_SplitHands : NoneType
  do_hands_per_file(infile, num)
  new_file(fileno)
  next_hand(infile)
  paragraphs(file, separator, addendum)
  process_hand(infile, outfile)
}
@enduml
