@startuml classes
set namespaceSeparator none
class "Betfair" as BetfairToFpdb.Betfair {
  codepage : str
  compiledPlayers : set
  filetype : str
  re_Action
  re_Antes
  re_Board
  re_BringIn
  re_Button
  re_CollectPot
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_ShowdownAction
  re_ShownCards
  re_SitsOut
  re_SplitHands
  siteId : int
  sitename : str
  compilePlayerRegexs(hand)
  determineGameType(handText)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readStudPlayerCards(hand, street)
  readSupportedGames()
}
@enduml
