@startuml classes
set namespaceSeparator none
class "BetOnline" as BetOnlineToFpdb.BetOnline {
  Lim_Blinds : dict
  codepage : tuple
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  mixes : dict
  re_Action
  re_Antes
  re_Board1
  re_Board2
  re_BringIn
  re_Button
  re_CollectPot
  re_DateTime1
  re_DateTime2
  re_GameInfo
  re_HandInfo1
  re_HandInfo2
  re_HeroCards
  re_Hole
  re_Identify
  re_JoinsTable
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_ShowdownAction
  re_ShownCards
  re_SplitHands
  re_TailSplitHands
  re_TotalPot
  re_sitsOut
  siteId : int
  sitename : str
  skin
  skin : str
  skins : dict
  substitutions : dict
  sym : dict
  compilePlayerRegexs(hand)
  determineGameType(handText)
  fixBlinds(hand)
  getTableTitleRe(type, table_name, tournament, table_number)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
  unknownPlayer(hand, pname)
}
@enduml
