@startuml classes
set namespaceSeparator none
class "BovadaSummary" as BovadaSummary.BovadaSummary {
  addOnCost : int
  buyin : int
  buyinCurrency : str
  codepage : tuple
  currency : str, NoneType
  entries : NoneType
  fee : int
  isAddOn : bool
  isRebuy : bool
  prizepool : NoneType
  re_AddOn
  re_Identify
  re_Ranking
  re_Rebuyin
  re_Stand
  rebuyCost : int
  startTime : datetime
  substitutions : dict
  tourNo
  tourneyName
  getSplitRe(head)
  parseSummary()
}
@enduml
