@startuml classes
set namespaceSeparator none
class "Cake" as CakeToFpdb.Cake {
  Lim_Blinds : dict
  codepage : tuple
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  re_Action
  re_Antes
  re_Board
  re_BringIn
  re_Button
  re_CoinFlip
  re_CollectPot
  re_DateTime
  re_Dealer
  re_Finished
  re_GameInfo
  re_HeroCards
  re_Identify
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_ReturnBet
  re_ShowDown
  re_ShowDownLeft
  re_ShownCards
  re_SplitHands
  re_Trim
  re_sitsOut
  siteId : int
  sitename : str
  substitutions : dict
  sym : dict
  compilePlayerRegexs(hand)
  convertMoneyString(type, match)
  determineGameType(handText)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
