@startuml classes
set namespaceSeparator none
class "GuiHandViewer" as GuiHandViewer.GuiHandViewer {
  cardImages : list
  colnum : dict
  config
  db
  deck_instance
  filterModel
  filters
  hands : dict
  handsFrame
  handsVBox
  main_window
  model
  replayer : NoneType
  sql
  view
  addHandRow(handid, hand)
  contextMenu(event)
  copyHandToClipboard(checkState, hand)
  filter_cards_cb(card)
  get_hand_ids_from_date_range(start, end)
  importhand(handid)
  init_card_images()
  is_row_in_card_filter(rownum)
  loadHands(checkState)
  rankedhand(hand, game)
  reload_hands(handids)
  render_cards(cardstring)
  row_activated(index)
}
@enduml
