@startuml classes
set namespaceSeparator none
class "GuiOddsCalc" as GuiOddsCalc.GuiOddsCalc {
  Lreq
  QLEboard
  QLEdeadcard
  QLEgame
  QLEhero
  QLEvilain1
  QLEvilain2
  QLEvilain3
  QLEvilain4
  QLEvilain5
  QLboard
  QLdeadcard
  QLgame
  QLhero
  QLvilain1
  QLvilain2
  QLvilain3
  QLvilain4
  QLvilain5
  QTcalc
  hbox
  hbox2
  hbox3
  load_button
  get_vbox()
  index_changed()
  load_result()
  warning_box(string, diatitle)
}
@enduml
