@startuml classes
set namespaceSeparator none
class "GuiReplayer" as GuiReplayer.GuiReplayer {
  buttonBox
  buttonBox2
  cardImages : list, NoneType
  cardheight : int
  cardwidth : int
  conf
  currency
  db
  deck_inst
  endButton
  handidx : int
  handlist
  info : str
  main_window
  newpot
  nextButton
  playPauseButton
  playTimer : NoneType
  playerBackdrop : NoneType
  playing : bool
  prevButton
  replayBox
  showCards
  sql
  startButton
  stateSlider
  states : list
  tableImage : NoneType
  end_clicked(checkState)
  importhand(handid)
  increment_state()
  keyPressEvent(event)
  next_clicked(checkState)
  paintEvent(event)
  play_clicked(checkState)
  play_hand(handidx)
  prev_clicked(checkState)
  renderCards(painter, cards, x, y)
  slider_changed(value)
  start_clicked(checkState)
  street_clicked(checkState, street)
}
class "ICM" as GuiReplayer.ICM {
  equities : list
  payouts
  stacks
  getEquities(total, player, depth)
  prepare()
}
class "Player" as GuiReplayer.Player {
  action : NoneType
  chips
  holecards
  justacted : bool
  name
  seat
  stack
  streetcards : dict
  x
  y
}
class "TableState" as GuiReplayer.TableState {
  allin : bool
  allinThisStreet : bool
  bet
  board
  called
  gamebase
  gametype
  newpot
  players : dict
  pot
  renderBoard : set
  street : NoneType
  endHand(collectees, returned)
  startPhase(phase)
  updateForAction(action)
}
@enduml
