@startuml classes
set namespaceSeparator none
class "GuiStove" as GuiStove.GuiStove {
  board
  boardtext : str
  conf
  ev : NoneType
  herorange : str
  mainHBox
  notebook
  outputlabel
  outstring : str
  p1_board
  p2_board
  parent
  villainrange : str
  createDrawTab()
  createFlopTab()
  createStudTab()
  create_combo_box(strings)
  get_active_text(combobox)
  get_vbox()
  set_board_flop(caller, widget)
  set_hero_cards_flop(caller, widget)
  set_output_label(string)
  set_villain_cards_flop(caller, widget)
  update_flop_output_pane(caller, widget)
  warning_box(string, diatitle)
}
@enduml
