@startuml classes
set namespaceSeparator none
class "GuiSessionViewer" as GuiSessionViewer.GuiSessionViewer {
  MYSQL_INNODB : int
  PGSQL : int
  SQLITE : int
  ax : NoneType
  canvas : NoneType
  columns : list
  conf
  cursor
  db
  debug : bool
  detailFilters : list
  fig : Figure, NoneType
  filterText : dict
  filters
  graphBox : NoneType
  liststore : NoneType
  main_vbox
  owner
  sql
  stats_frame
  times : list
  view : NoneType
  window
  addTable(frame, results)
  clearGraphData()
  createStatsPane(frame, playerids, sitenos, games, currencies, limits, seats)
  fillStatsFrame(frame)
  generateDatasets(playerids, sitenos, games, currencies, limits, seats)
  generateGraph(quotes)
  refreshStats(checkState)
  row_activated(index)
}
@enduml
