@startuml classes
set namespaceSeparator none
class "GuiTourneyImport" as GuiTourneyImport.GuiTourneyImport {
  cbfilter
  chooser
  config
  importer
  lab_filter
  lab_spacer
  load_button
  parent : NoneType
  settings
  table
  vbox
  get_vbox()
  load_clicked(widget, data)
  progressNotify()
}
class "ProgressBar" as GuiTourneyImport.ProgressBar {
  count
  fraction : int
  parent
  pbar
  progress
  progresstext
  sum
  title : str
  progress_update(file, count)
}
class "SummaryImporter" as GuiTourneyImport.SummaryImporter {
  caller : NoneType
  config
  database
  dirlist : dict
  filelist : dict
  monitor : bool
  parent : NoneType
  settings : dict
  sql : NoneType
  updatedsize : dict
  updatedtime : dict
  updatetime : dict
  addImportDirectory(dir, monitor, site, tsc)
  addImportFile(filename, site, tsc)
  addImportFileOrDir(inputPath, site)
  clearFileList()
  importFile(filename, tsc, site)
  runImport()
  runUpdated()
  setPrintTestData(value)
}
GuiTourneyImport.SummaryImporter --* GuiTourneyImport.GuiTourneyImport : importer
@enduml
