@startuml classes
set namespaceSeparator none
class "Flop_Mucked" as Mucked.Flop_Mucked {
  card_height
  card_images
  card_width
  displayed : bool
  timer_on : bool
  uses_timer : bool
  button_press_cb(widget, event, i)
  create_common(x, y)
  create_contents(container, i)
  expose_all()
  save_layout()
  timerEvent(event)
  update_contents(container, i)
  update_gui(new_hand_id)
}
class "Stud_cards" as Mucked.Stud_cards {
  card_images
  cols : int
  config
  container
  eb : dict
  grid
  grid_contents : dict
  params
  parent
  rows : int
  tips : list
  clear()
  create(container)
  get_screen_name(seat_no)
  update_data(new_hand_id, db_connection)
  update_gui(new_hand_id)
}
class "Stud_list" as Mucked.Stud_list {
  config
  container
  hero
  info_row : tuple
  liststore
  mucked_cards
  params
  parent
  treeview
  winners
  create(container)
  get_hero_cards(hero)
  update_data(new_hand_id, db_connection)
  update_gui(new_hand_id)
}
class "Stud_mucked" as Mucked.Stud_mucked {
  config
  container
  hero : str
  hud
  mucked_cards
  mucked_list
  params
  vbox
  create()
  update_data(new_hand_id, db_connection)
  update_gui(new_hand_id)
}
Mucked.Stud_cards --* Mucked.Stud_list : mucked_cards
Mucked.Stud_cards --* Mucked.Stud_mucked : mucked_cards
Mucked.Stud_list --* Mucked.Stud_mucked : mucked_list
@enduml
