@startuml classes
set namespaceSeparator none
class "RushNotes" as RushNotesAux.RushNotes {
  active : bool
  config
  heroid
  hud
  notefile
  queuefile
  rushtables : tuple
  update_data(new_hand_id, db_connection)
}
@enduml
