@startuml classes
set namespaceSeparator none
class "Sitename" as SitenameSummary.Sitename {
  buyin : int
  codepage : list
  currency : str
  entries : int
  fee : int
  games : dict
  limits : dict
  prizepool : int
  re_Currency
  re_DateTime
  re_Player
  re_SplitTourneys
  re_TourNo
  re_TourneyInfo
  substitutions : dict
  tourNo : str
  getSplitRe(head)
  parseSummary()
}
@enduml
