@startuml classes
set namespaceSeparator none
class "Archive" as Archive.Archive {
  archivePath : NoneType
  config : NoneType
  ftype : str
  handList : dict
  path : NoneType
  positionsArchive : dict
  sessionsArchive : dict
  startCardsArchive : dict
  addHand(hand, write)
  addPositionsHands(type, activeSeats, position, wid, siteId, hids)
  addSessionHands(type, sid, id, hids)
  addStartCardsHands(category, type, startCards, wid, siteId, hids)
  createSession(sid)
  fileInfo(path, site, filter, filter_name, obj, summary)
  fileOrZip(path)
  getFile(path)
  getSiteSplit()
  mergeFiles(path1, path2)
  mergeSessions(oldsid, newsid)
  mergeSubSessions(type, sid, oldId, newId, hids)
  quickImport(userid, filtertype, game, filter, settings, tz)
  unzipAll()
  unzipFile(path)
  writeHands(doinsert)
  zipAll()
  zipFile(path)
}
class "FPDBArchive" as Archive.FPDBArchive {
  handText
  hid
}
@enduml
