@startuml classes
set namespaceSeparator none
class "Classic_HUD" as Aux_Classic_Hud.Classic_HUD {
  aw_class_label
  aw_class_stat
  aw_class_table_mw
  aw_class_window
}
class "Classic_Stat_Window" as Aux_Classic_Hud.Classic_Stat_Window {
  button_press_middle(event)
  update_contents(i)
}
class "Classic_label" as Aux_Classic_Hud.Classic_label {
}
class "Classic_stat" as Aux_Classic_Hud.Classic_stat {
  click
  hudcolor
  hudprefix
  hudsuffix
  popup
  stat_hicolor : str
  stat_hith : str
  stat_locolor : str
  stat_loth : str
  tip
  update(player_id, stat_dict)
}
class "Classic_table_mw" as Aux_Classic_Hud.Classic_table_mw {
}
Aux_Classic_Hud.Classic_Stat_Window --* Aux_Classic_Hud.Classic_HUD : aw_class_window
Aux_Classic_Hud.Classic_label --* Aux_Classic_Hud.Classic_HUD : aw_class_label
Aux_Classic_Hud.Classic_stat --* Aux_Classic_Hud.Classic_HUD : aw_class_stat
Aux_Classic_Hud.Classic_table_mw --* Aux_Classic_Hud.Classic_HUD : aw_class_table_mw
@enduml
