@startuml classes
set namespaceSeparator none
class "Bovada" as BovadaToFpdb.Bovada {
  Lim_Blinds : dict
  codepage : tuple
  compiledPlayers : set
  copyGameHeader : bool
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  playersMap : dict
  re_Action
  re_Antes
  re_Board1
  re_Board2 : dict
  re_Bounty
  re_BringIn
  re_Button
  re_Buyin
  re_CollectPot1
  re_CollectPot2
  re_DateTime
  re_Dealt
  re_GameInfo
  re_HeroCards
  re_Hole_Third
  re_Identify
  re_Knockout
  re_PlayerInfo
  re_PlayerInfoStud
  re_PlayerSeat
  re_PostBB
  re_PostBoth
  re_PostSB
  re_ReturnBet
  re_ShowdownAction
  re_SplitHands
  re_Stakes
  re_Summary
  re_TailSplitHands
  siteId : int
  sitename : str
  substitutions : dict
  summaryInFile : bool
  sym : dict
  allInBlind(hand, street, action, actiontype)
  compilePlayerRegexs(hand)
  determineGameType(handText)
  fixBlinds(hand)
  markStreets(hand)
  parseHeader(handText, whole_file)
  playerSeatFromPosition(source, handid, position)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
  readTourneyResults(hand)
}
@enduml
