@startuml classes
set namespaceSeparator none
class "DerivedStats" as DerivedStats.DerivedStats {
  hands : dict
  handsactions : dict
  handsplayers : dict
  handspots : list
  handsstove : list
  aggr(hand, i)
  assembleHands(hand)
  assembleHandsActions(hand)
  assembleHandsPlayers(hand)
  assembleHandsPots(hand)
  assembleHandsStove(hand)
  assembleHudCache(hand)
  awardPots(hand)
  betStreet(actions, street, player)
  bets(hand, i)
  calc34BetStreet0(hand)
  calcCBets(hand)
  calcCalledRaiseStreet0(hand)
  calcCheckCallRaise(hand)
  calcEffectiveStack(hand)
  calcSteals(hand)
  calls(hand, i)
  countPlayers(hand)
  firstsBetOrRaiser(actions)
  foldTofirstsBetOrRaiser(actions, street, aggressor)
  folds(hand, i)
  getAllInEV(hand, evalgame, holeplayers, boards, streets, holecards)
  getBoardsDict(hand, base, streets)
  getBoardsList(hand)
  getHands()
  getHandsActions()
  getHandsPlayers()
  getHandsPots()
  getHandsStove()
  getStats(hand)
  lastBetOrRaiser(actions, street)
  noBetsBefore(actions, street, player)
  pfba(actions, f, l)
  pfbao(actions, f, l, unique)
  playersAtStreetX(hand)
  raises(hand, i)
  setPositions(hand)
  streetXRaises(hand)
  vpip(hand)
}
@enduml
