@startuml classes
set namespaceSeparator none
class "DetectInstalledSites" as DetectInstalledSites.DetectInstalledSites {
  Config
  detected : str
  herofound : str
  heroname : str
  hhpath : str
  hhpathfound : str
  sitename : str
  sitestatusdict : dict
  supportedPlatforms : list
  supportedSites : list
  tspath : str
  tspathfound : str
  detect(siteToDetect)
  detectFullTilt()
  detectMergeNetwork()
  detectPartyPoker()
  detectPokerStars()
}
@enduml
