@startuml classes
set namespaceSeparator none
class "GuiBulkImport" as GuiBulkImport.GuiBulkImport {
  allowThreads : bool
  chooseButton
  config
  importDir
  importer
  load_button
  n_hands_in_db
  settings
  browseClicked()
  get_vbox()
  load_clicked()
}
@enduml
