@startuml classes
set namespaceSeparator none
class "AddDB" as GuiDatabase.AddDB {
  cb_dbms
  config
  dbnames : dict
  e_db_desc
  e_db_name
  e_host
  e_password
  e_username
  l_host
  l_password
  l_username
  check_fields()
  db_name_changed(widget, event, data)
  db_type_changed(widget, data)
  run()
}
class "GuiDatabase" as GuiDatabase.GuiDatabase {
  COL_DBMS : int
  COL_DESC : int
  COL_DFLT : int
  COL_HOST : int
  COL_ICON : int
  COL_NAME : int
  COL_PASS : int
  COL_USER : int
  MODEL_DBMS : int
  MODEL_DESC : int
  MODEL_DFLT : int
  MODEL_DFLTIC : int
  MODEL_HOST : int
  MODEL_NAME : int
  MODEL_PASS : int
  MODEL_STATIC : int
  MODEL_STATUS : int
  MODEL_USER : int
  action_area
  changes : bool
  config
  dia
  listcols : list
  liststore
  listview
  main_window
  scrolledwindow
  vbox
  addDB(widget, data)
  addTextColumn(title, n, editable)
  addTextObjColumn(title, viewcol, storecol, editable)
  check_new_name(path, new_text)
  dialog_response_cb(dialog, response_id)
  edited_cb(cell, path, new_text, user_data)
  get_dialog()
  loadDbs()
  refresh(widget, data)
  selectTest(widget, event)
  setDefaultDB(row)
  sortCols(col, n)
  testDB(config, dbms, dbms_num, name, user, passwd, host)
}
class "InfoBox" as GuiDatabase.InfoBox {
  add_msg(str1, run, destroy)
}
class "SideButton" as GuiDatabase.SideButton {
}
@enduml
