@startuml classes
set namespaceSeparator none
class "GuiLogView" as GuiLogView.GuiLogView {
  closeq
  config
  liststore
  listview
  logfile
  main_window
  copy_to_clipboard(checkState)
  dialog_response_cb(dialog, response_id)
  get_dialog()
  loadLog()
  refresh(checkState)
}
@enduml
