@startuml classes
set namespaceSeparator none
class "GuiPrefs" as GuiPrefs.GuiPrefs {
  config
  configView
  doc
  root
  addTreeRows(parent, node)
  rewriteText(s)
  updateConf(item, column)
}
@enduml
