@startuml classes
set namespaceSeparator none
class "GuiPositionalStats" as GuiPositionalStats.GuiPositionalStats {
  MYSQL_INNODB : int
  PGSQL : int
  SQLITE : int
  activesite : NoneType
  columns : list
  conf
  cursor
  db
  debug : bool
  filters
  main_hbox
  posncols : tuple
  posnheads : tuple
  sql
  stat_table : NoneType
  stats_frame : NoneType
  stats_vbox : NoneType
  createStatsTable(vbox, playerids, sitenos, limits, seats, dates)
  fillStatsFrame(vbox)
  get_vbox()
  refineQuery(query, playerids, sitenos, limits, seats, dates)
  refreshStats(widget, data)
  toggleCallback(widget, data)
}
@enduml
