@startuml classes
set namespaceSeparator none
class "GuiTourneyPlayerStats" as GuiTourneyPlayerStats.GuiTourneyPlayerStats {
  cols_to_show : list
  columns : list
  conf
  cursor
  db
  debug : bool
  detailFilters : list
  filters
  listcols : list
  liststore : list
  main_window
  sql
  stats_frame : NoneType
  stats_vbox : NoneType
  addGrid(vbox, query, numTourneys, tourneyTypes, playerids, sitenos, seats)
  createStatsTable(vbox, tourneyTypes, playerids, sitenos, seats)
  fillStatsFrame(vbox)
  refineQuery(query, numTourneys, tourneyTypes, playerids, sitenos, seats)
  refreshStats(widget)
  reset_style_render_func(treeviewcolumn, cell, model, iter)
  sortCols(col, nums)
}
@enduml
