@startuml classes
set namespaceSeparator none
class "HUD_main" as HUD_main.HUD_main {
  blacklist : list
  config
  db_connection
  db_name : str
  deck
  hero : dict
  hero_ids : dict
  hud_dict : dict
  hud_params
  label
  main_window
  stdinReader
  stdinThread
  vb
  blacklist_hud(event, table)
  check_tables()
  client_destroyed(widget, hud)
  client_moved(widget, hud)
  client_resized(widget, hud)
  create_HUD(new_hand_id, table, temp_key, max, poker_game, type, stat_dict, cards)
  destroy()
  get_cards(new_hand_id, poker_game)
  kill_hud(event, table)
  read_stdin(new_hand_id)
  table_is_stale(hud)
  table_title_changed(widget, hud)
  timerEvent(event)
  update_HUD(new_hand_id, table_name, config)
}
class "Reader" as HUD_main.Reader {
  handRead
  readStdin()
}
HUD_main.Reader --* HUD_main.HUD_main : stdinReader
@enduml
