@startuml classes
set namespaceSeparator none
class "FPDBFile" as IdentifySite.FPDBFile {
  archive : bool
  archive : bool
  archiveDivider : bool
  archiveDivider : bool
  archiveHead : bool
  archiveHead : bool
  ftype : NoneType
  ftype : str
  gametype : bool
  hero : str
  hero : str
  kodec
  kodec : NoneType
  path
  path : str
  site
  site : NoneType
}
class "IdentifySite" as IdentifySite.IdentifySite {
  codepage : tuple
  config
  filelist : dict
  re_Identify_PT
  re_SumIdentify_PT
  sitelist : dict
  clear_filelist()
  fetchGameTypes()
  generateSiteList(hhcs)
  getFilesForSite(sitename, ftype)
  get_filelist()
  get_fobj(file)
  idSite(path, whole_file, kodec)
  processFile(path)
  read_file(in_path)
  scan(path)
  walkDirectory(dir, sitelist)
}
class "Site" as IdentifySite.Site {
  codepage
  copyGameHeader
  filter_name
  hhc_fname
  line_addendum : str
  line_delimiter : str, NoneType
  name
  re_HeroCards : NoneType
  re_HeroCards1
  re_HeroCards2
  re_Identify
  re_SplitHands
  re_SumIdentify
  spaces : bool
  summary : NoneType
  summaryInFile
  getAddendum(filter_name)
  getDelimiter(filter_name)
  getHeroRegex(obj, filter_name)
}
IdentifySite.Site --* IdentifySite.FPDBFile : site
@enduml
