@startuml classes
set namespaceSeparator none
class "iPokerSummary" as iPokerSummary.iPokerSummary {
  buyin : int
  buyinCurrency : str
  codepage : list
  currencies : dict
  currency : NoneType, str
  entries : NoneType
  fee : int
  games : dict
  limits : dict
  months : dict
  prizepool : NoneType
  re_Buyin
  re_DateTime1
  re_DateTime2
  re_DateTime3
  re_FPP
  re_GameInfoTrny
  re_GameType
  re_Identify
  re_Place
  re_TotalBuyin
  re_TourNo
  startTime : datetime
  substitutions : dict
  tourNo
  tourneyName
  convert_to_decimal(string)
  getSplitRe(head)
  parseSummary()
}
@enduml
