@startuml classes
set namespaceSeparator none
class "KingsClub" as KingsClubToFpdb.KingsClub {
  Lim_Blinds : dict
  codepage : tuple
  compiledPlayers : set
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  mixes : dict
  re_Action
  re_Antes
  re_Board
  re_Board2
  re_Bounty
  re_BringIn
  re_Button
  re_Cancelled
  re_CashedOut
  re_CollectPot
  re_DateTime
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_PostStraddle
  re_Progressive
  re_Rake
  re_RankOther
  re_STP
  re_ShowdownAction
  re_Split
  re_SplitHands
  re_TailSplitHands
  re_TourNo
  re_Uncalled
  re_WinningRankOne
  re_WinningRankOther
  re_sitsOut
  siteId : int
  sitename : str
  substitutions : dict
  sym : dict
  compilePlayerRegexs(hand)
  determineGameType(handText)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readSTP(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
