@startuml classes
set namespaceSeparator none
class "Merge" as MergeToFpdb.Merge {
  Lim_Blinds : dict
  Multigametypes : dict
  Structures
  codepage : tuple
  copyGameHeader : bool
  filetype : str
  games : dict
  info : dict
  limits : dict
  maxseats
  mixes : dict
  re_Action
  re_AllActions
  re_Antes
  re_Board
  re_BringIn
  re_Button
  re_Buyin
  re_Cancelled
  re_CollectPot
  re_Connection
  re_DateTime
  re_EndOfHand
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_LeaveTable
  re_PlayMoney
  re_PlayerInfo
  re_PlayerOut
  re_PostBB
  re_PostBoth
  re_PostSB
  re_ShownCards
  re_SitsOut
  re_SplitHands
  re_TailSplitHands
  re_secondGame
  siteId : int
  sitename : str
  summaryInFile : bool
  adjustMergeTourneyStack(hand, player, amount)
  compilePlayerRegexs(hand)
  determineErrorType(hand, function)
  determineGameType(handText)
  fixTourBlinds(hand, allinBlinds)
  getTableTitleRe(type, table_name, tournament, table_number)
  markStreets(hand)
  mergeMultigametypes(handText)
  parseHeader(handText, whole_file)
  playerNameFromSeatNo(seatNo, hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSupportedGames()
}
@enduml
