@startuml classes
set namespaceSeparator none
class "Table" as OSXTables.Table {
  number : int, NoneType
  title
  find_table_parameters()
  get_geometry()
  get_window_title()
  topify(window)
}
@enduml
