@startuml classes
set namespaceSeparator none
class "PacificPoker" as PacificPokerToFpdb.PacificPoker {
  codepage : tuple
  currencies : dict
  filetype : str
  games : dict
  limits : dict
  mixes : dict
  re_Action
  re_Antes
  re_Board
  re_BringIn
  re_Button
  re_CollectPot
  re_DateTime
  re_GameInfo
  re_HandInfo
  re_HeroCards
  re_Identify
  re_PlayerInfo
  re_PostBB
  re_PostBoth
  re_PostSB
  re_ShowdownAction
  re_ShownCards
  re_Spanish_10
  re_SplitHands
  re_TailSplitHands
  re_sitsOut
  short_subst : dict
  siteId : int
  sitename : str
  status : bool
  substitutions : dict
  sym : dict
  allInBlind(hand, street, action, actiontype)
  compilePlayerRegexs(hand)
  determineGameType(handText)
  getTableTitleRe(type, table_name, tournament, table_number)
  markStreets(hand)
  readAction(hand, street)
  readAntes(hand)
  readBlinds(hand)
  readBringIn(hand)
  readButton(hand)
  readCollectPot(hand)
  readCommunityCards(hand, street)
  readHandInfo(hand)
  readHoleCards(hand)
  readPlayerStacks(hand)
  readShowdownActions(hand)
  readShownCards(hand)
  readSummaryInfo(summaryInfoList)
  readSupportedGames()
  splitCards(cards)
}
@enduml
