@startuml classes
set namespaceSeparator none
class "Table_Window" as TableWindow.Table_Window {
  config
  game : bool
  gdkhandle : NoneType
  height
  hud : NoneType
  name : NoneType
  number : NoneType
  oldheight
  oldwidth
  oldx
  oldy
  search_string
  site
  table : bool, int
  tableno_re
  tournament : NoneType, int
  type : str
  width
  x
  y
  check_bad_words(title)
  check_loc()
  check_size()
  check_table()
  get_game()
  get_table_no()
  has_table_title_changed(hud)
}
@enduml
