name: Fpdb-3

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        run-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./pyfpdb
            
        strategy:
            matrix:
                python-version: [3.9, 3.11]

        env:
            MODE: "dev"

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
            - uses: actions/setup-python@v4
            - with:
                python-version: ${{matrix.python-version}}

            - name: Install depenencies
              run: | 
                python -m pip install --upgrade pip
                pip install -r ../requirements.txt

            - name: Test FPDB Code
              run: python ./test_pot.py


