name: Fpdb-3

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        run-on: [ubuntu-latest, windows-latest, macos-latest]
        defaults:
            run:
                working-directory: ./pyfpdb
            
        strategy:
            matrix:
                python-version: [3.9, 3.11]

        env:
            MODE: "dev"

        steps:
            - uses: actions/checkout@v3

